// Biology Test Banks - 50 tests x 15 questions = 750 questions
// Grades 4-10, ~2 questions per grade level per test
// Topics: living things, plants, animals, habitats, cells, food chains,
// photosynthesis, body systems, genetics, DNA, evolution, ecology,
// macromolecules, protein synthesis, mitosis/meiosis, enzymes
// All answers verified correct. No duplicate questions across tests.

const biologyTestBanks = [
  [
    { id: 1, subject: 'Biology', grade: 4, question: 'What do plants need to make their own food?', options: ['Rocks and sand', 'Sunlight, water, and carbon dioxide', 'Meat and bones', 'Only soil'], answer: 1 },
    { id: 2, subject: 'Biology', grade: 4, question: 'Which of the following is a living thing?', options: ['A rock', 'A tree', 'A chair', 'A glass of water'], answer: 1 },
    { id: 3, subject: 'Biology', grade: 5, question: 'What is the basic unit of life?', options: ['Atom', 'Molecule', 'Cell', 'Organ'], answer: 2 },
    { id: 4, subject: 'Biology', grade: 5, question: 'Which part of the plant absorbs water from the soil?', options: ['Leaves', 'Stem', 'Roots', 'Flower'], answer: 2 },
    { id: 5, subject: 'Biology', grade: 6, question: 'What is a food chain?', options: ['A chain made of food', 'The path of energy from one organism to another', 'A type of recipe', 'A grocery store aisle'], answer: 1 },
    { id: 6, subject: 'Biology', grade: 6, question: 'Which organ pumps blood through your body?', options: ['Lungs', 'Brain', 'Heart', 'Stomach'], answer: 2 },
    { id: 7, subject: 'Biology', grade: 7, question: 'What is photosynthesis?', options: ['Animals eating plants', 'Plants converting sunlight into food', 'Fish breathing underwater', 'Rocks breaking down over time'], answer: 1 },
    { id: 8, subject: 'Biology', grade: 7, question: 'What organelle is known as the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Cell wall'], answer: 2 },
    { id: 9, subject: 'Biology', grade: 8, question: 'What does DNA stand for?', options: ['Deoxyribonucleic acid', 'Dinitrogen acid', 'Dynamic nuclear atom', 'Dual nitrogen arrangement'], answer: 0 },
    { id: 10, subject: 'Biology', grade: 8, question: 'What type of cell division produces two identical daughter cells?', options: ['Meiosis', 'Mitosis', 'Binary fission', 'Budding'], answer: 1 },
    { id: 11, subject: 'Biology', grade: 9, question: 'Which macromolecule stores genetic information?', options: ['Carbohydrates', 'Lipids', 'Proteins', 'Nucleic acids'], answer: 3 },
    { id: 12, subject: 'Biology', grade: 9, question: 'What is natural selection?', options: ['Humans choosing which animals to breed', 'Survival and reproduction of organisms best adapted to their environment', 'Random changes in a population', 'Animals migrating to new areas'], answer: 1 },
    { id: 13, subject: 'Biology', grade: 10, question: 'During which phase of mitosis do chromosomes line up at the cell equator?', options: ['Prophase', 'Metaphase', 'Anaphase', 'Telophase'], answer: 1 },
    { id: 14, subject: 'Biology', grade: 10, question: 'What is the role of enzymes in biological reactions?', options: ['They provide energy', 'They act as catalysts to speed up reactions', 'They store genetic information', 'They transport oxygen'], answer: 1 },
    { id: 15, subject: 'Biology', grade: 4, question: 'Which animal group has feathers?', options: ['Mammals', 'Reptiles', 'Birds', 'Fish'], answer: 2 }
  ],
  [
    { id: 16, subject: 'Biology', grade: 4, question: 'What do herbivores eat?', options: ['Meat', 'Plants', 'Both meat and plants', 'Rocks'], answer: 1 },
    { id: 17, subject: 'Biology', grade: 4, question: 'What do fish use to breathe underwater?', options: ['Lungs', 'Gills', 'Skin', 'Fins'], answer: 1 },
    { id: 18, subject: 'Biology', grade: 5, question: 'What gas do animals breathe out that plants use?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium'], answer: 2 },
    { id: 19, subject: 'Biology', grade: 5, question: 'What is a habitat?', options: ['A type of animal', 'The natural home of an organism', 'A kind of plant', 'A weather pattern'], answer: 1 },
    { id: 20, subject: 'Biology', grade: 6, question: 'What is the green pigment in plants called?', options: ['Melanin', 'Chlorophyll', 'Hemoglobin', 'Carotene'], answer: 1 },
    { id: 21, subject: 'Biology', grade: 6, question: 'Which type of animal is cold-blooded and has scales?', options: ['Mammal', 'Bird', 'Reptile', 'Amphibian'], answer: 2 },
    { id: 22, subject: 'Biology', grade: 7, question: 'What structure controls what enters and leaves a cell?', options: ['Nucleus', 'Cell membrane', 'Ribosome', 'Cytoplasm'], answer: 1 },
    { id: 23, subject: 'Biology', grade: 7, question: 'In a food chain, what is a primary consumer?', options: ['A plant', 'An herbivore that eats plants', 'A top predator', 'A decomposer'], answer: 1 },
    { id: 24, subject: 'Biology', grade: 8, question: 'What are genes made of?', options: ['Proteins', 'Lipids', 'DNA', 'Carbohydrates'], answer: 2 },
    { id: 25, subject: 'Biology', grade: 8, question: 'Which organ system removes waste from the blood?', options: ['Digestive system', 'Urinary system', 'Respiratory system', 'Endocrine system'], answer: 1 },
    { id: 26, subject: 'Biology', grade: 9, question: 'What is the function of ribosomes?', options: ['Energy production', 'Protein synthesis', 'Cell division', 'Waste removal'], answer: 1 },
    { id: 27, subject: 'Biology', grade: 9, question: 'Which type of macromolecule includes sugars and starches?', options: ['Proteins', 'Lipids', 'Carbohydrates', 'Nucleic acids'], answer: 2 },
    { id: 28, subject: 'Biology', grade: 10, question: 'What is the difference between mitosis and meiosis?', options: ['Mitosis produces 4 cells; meiosis produces 2', 'Mitosis is for growth; meiosis produces gametes', 'They are the same process', 'Meiosis only occurs in plants'], answer: 1 },
    { id: 29, subject: 'Biology', grade: 10, question: 'What is the substrate of an enzyme?', options: ['The product of the reaction', 'The molecule the enzyme acts upon', 'The enzyme itself', 'The cofactor'], answer: 1 },
    { id: 30, subject: 'Biology', grade: 5, question: 'Which body system is responsible for breaking down food?', options: ['Respiratory system', 'Circulatory system', 'Digestive system', 'Nervous system'], answer: 2 }
  ],
  [
    { id: 31, subject: 'Biology', grade: 4, question: 'Which of these is NOT a characteristic of living things?', options: ['Growth', 'Reproduction', 'Movement caused by wind', 'Response to stimuli'], answer: 2 },
    { id: 32, subject: 'Biology', grade: 4, question: 'What part of a plant makes seeds?', options: ['Root', 'Stem', 'Leaf', 'Flower'], answer: 3 },
    { id: 33, subject: 'Biology', grade: 5, question: 'What is pollination?', options: ['When roots absorb water', 'The transfer of pollen from one flower to another', 'When leaves fall off trees', 'When seeds sprout'], answer: 1 },
    { id: 34, subject: 'Biology', grade: 5, question: 'Which system in the body is made up of bones?', options: ['Muscular system', 'Skeletal system', 'Nervous system', 'Digestive system'], answer: 1 },
    { id: 35, subject: 'Biology', grade: 6, question: 'What is the role of decomposers in an ecosystem?', options: ['They produce food', 'They hunt prey', 'They break down dead organisms', 'They photosynthesize'], answer: 2 },
    { id: 36, subject: 'Biology', grade: 6, question: 'Which part of the cell contains genetic material?', options: ['Cell membrane', 'Cytoplasm', 'Nucleus', 'Vacuole'], answer: 2 },
    { id: 37, subject: 'Biology', grade: 7, question: 'What is the difference between plant and animal cells?', options: ['Animal cells have a nucleus, plant cells do not', 'Plant cells have a cell wall and chloroplasts; animal cells do not', 'They are identical', 'Animal cells have chloroplasts'], answer: 1 },
    { id: 38, subject: 'Biology', grade: 7, question: 'What is the function of the circulatory system?', options: ['To break down food', 'To transport blood, nutrients, and oxygen throughout the body', 'To remove carbon dioxide only', 'To produce hormones'], answer: 1 },
    { id: 39, subject: 'Biology', grade: 8, question: 'What is an allele?', options: ['A type of cell', 'A form of a gene', 'A chromosome pair', 'A type of protein'], answer: 1 },
    { id: 40, subject: 'Biology', grade: 8, question: 'Which molecule carries amino acids to the ribosome during translation?', options: ['mRNA', 'tRNA', 'rRNA', 'DNA'], answer: 1 },
    { id: 41, subject: 'Biology', grade: 9, question: 'What bonds hold the two strands of DNA together?', options: ['Ionic bonds', 'Covalent bonds', 'Hydrogen bonds', 'Peptide bonds'], answer: 2 },
    { id: 42, subject: 'Biology', grade: 9, question: 'Which process converts glucose into ATP in the absence of oxygen?', options: ['Aerobic respiration', 'Fermentation', 'Photosynthesis', 'Chemosynthesis'], answer: 1 },
    { id: 43, subject: 'Biology', grade: 10, question: 'What is the lock-and-key model of enzyme action?', options: ['Enzymes change shape randomly', 'The substrate fits precisely into the enzyme active site', 'Enzymes lock onto any molecule', 'Keys are used to open cell membranes'], answer: 1 },
    { id: 44, subject: 'Biology', grade: 10, question: 'During meiosis, how many daughter cells are produced?', options: ['2', '3', '4', '8'], answer: 2 },
    { id: 45, subject: 'Biology', grade: 6, question: 'What is an ecosystem?', options: ['A single organism', 'A community of living things and their environment', 'A type of biome', 'Only the plants in an area'], answer: 1 }
  ],
  [
    { id: 46, subject: 'Biology', grade: 4, question: 'What is the largest organ in the human body?', options: ['Heart', 'Brain', 'Skin', 'Liver'], answer: 2 },
    { id: 47, subject: 'Biology', grade: 4, question: 'Which sense organ detects light?', options: ['Ear', 'Nose', 'Eye', 'Tongue'], answer: 2 },
    { id: 48, subject: 'Biology', grade: 5, question: 'How do seeds travel to new places?', options: ['Only by rolling', 'By wind, water, and animals', 'They cannot move', 'Only by water'], answer: 1 },
    { id: 49, subject: 'Biology', grade: 5, question: 'What is the job of white blood cells?', options: ['Carry oxygen', 'Fight infections', 'Clot blood', 'Carry nutrients'], answer: 1 },
    { id: 50, subject: 'Biology', grade: 6, question: 'What is the function of the stomata in leaves?', options: ['Absorb water', 'Allow gas exchange', 'Support the leaf', 'Store food'], answer: 1 },
    { id: 51, subject: 'Biology', grade: 6, question: 'What type of organism makes its own food using sunlight?', options: ['Consumer', 'Decomposer', 'Producer', 'Scavenger'], answer: 2 },
    { id: 52, subject: 'Biology', grade: 7, question: 'What is the function of the respiratory system?', options: ['To digest food', 'To exchange oxygen and carbon dioxide', 'To pump blood', 'To filter waste'], answer: 1 },
    { id: 53, subject: 'Biology', grade: 7, question: 'What are producers in a food chain?', options: ['Animals that eat other animals', 'Organisms that make their own food', 'Animals that eat plants', 'Organisms that break down dead matter'], answer: 1 },
    { id: 54, subject: 'Biology', grade: 8, question: 'What is a dominant trait?', options: ['A trait that is always harmful', 'A trait expressed when at least one dominant allele is present', 'A trait that skips generations', 'A trait only found in males'], answer: 1 },
    { id: 55, subject: 'Biology', grade: 8, question: 'What is the function of the cell wall in plant cells?', options: ['Controls what enters the cell', 'Provides rigid structural support', 'Produces energy', 'Contains DNA'], answer: 1 },
    { id: 56, subject: 'Biology', grade: 9, question: 'What are the four nitrogenous bases in DNA?', options: ['Adenine, thymine, guanine, cytosine', 'Adenine, uracil, guanine, cytosine', 'Alanine, threonine, glycine, cysteine', 'Arginine, tryptophan, glutamine, cysteine'], answer: 0 },
    { id: 57, subject: 'Biology', grade: 9, question: 'What is the theory of evolution by natural selection?', options: ['All species were created at the same time', 'Species change over time through survival of the fittest', 'Evolution only affects plants', 'Organisms choose how to evolve'], answer: 1 },
    { id: 58, subject: 'Biology', grade: 10, question: 'What is crossing over in meiosis?', options: ['Cells dividing in half', 'Exchange of genetic material between homologous chromosomes', 'DNA replication errors', 'Movement of cells across a membrane'], answer: 1 },
    { id: 59, subject: 'Biology', grade: 10, question: 'Which macromolecule is composed of amino acids?', options: ['Carbohydrates', 'Lipids', 'Proteins', 'Nucleic acids'], answer: 2 },
    { id: 60, subject: 'Biology', grade: 7, question: 'What is the equation for photosynthesis?', options: ['Oxygen + glucose -> carbon dioxide + water', 'Carbon dioxide + water -> glucose + oxygen', 'Glucose -> carbon dioxide + water + ATP', 'Nitrogen + water -> ammonia + oxygen'], answer: 1 }
  ],
  [
    { id: 61, subject: 'Biology', grade: 4, question: 'What do carnivores eat?', options: ['Plants', 'Meat', 'Rocks', 'Sunlight'], answer: 1 },
    { id: 62, subject: 'Biology', grade: 4, question: 'What covers the body of a reptile?', options: ['Fur', 'Feathers', 'Scales', 'Smooth skin'], answer: 2 },
    { id: 63, subject: 'Biology', grade: 5, question: 'Which of these animals is an amphibian?', options: ['Snake', 'Frog', 'Eagle', 'Shark'], answer: 1 },
    { id: 64, subject: 'Biology', grade: 5, question: 'What is the process by which a caterpillar becomes a butterfly?', options: ['Evolution', 'Metamorphosis', 'Germination', 'Pollination'], answer: 1 },
    { id: 65, subject: 'Biology', grade: 6, question: 'What is a food web?', options: ['A single food chain', 'Multiple interconnected food chains in an ecosystem', 'A spider web made of food', 'A type of fishing net'], answer: 1 },
    { id: 66, subject: 'Biology', grade: 6, question: 'Which organelle is responsible for photosynthesis?', options: ['Mitochondria', 'Chloroplast', 'Ribosome', 'Nucleus'], answer: 1 },
    { id: 67, subject: 'Biology', grade: 7, question: 'What is cellular respiration?', options: ['Breathing in and out', 'The process cells use to break down glucose for energy', 'Photosynthesis in reverse only', 'Cell division'], answer: 1 },
    { id: 68, subject: 'Biology', grade: 7, question: 'What is the function of the Golgi apparatus?', options: ['Produces energy', 'Packages and ships proteins', 'Stores DNA', 'Controls cell division'], answer: 1 },
    { id: 69, subject: 'Biology', grade: 8, question: 'What is a Punnett square used for?', options: ['Measuring cell size', 'Predicting the probability of offspring genotypes', 'Counting chromosomes', 'Mapping ecosystems'], answer: 1 },
    { id: 70, subject: 'Biology', grade: 8, question: 'What is a recessive trait?', options: ['A trait always expressed', 'A trait only expressed when two recessive alleles are present', 'The stronger trait', 'A trait found only in plants'], answer: 1 },
    { id: 71, subject: 'Biology', grade: 9, question: 'What is transcription in biology?', options: ['Copying a book', 'The process of copying DNA into mRNA', 'Translating proteins', 'Cell division'], answer: 1 },
    { id: 72, subject: 'Biology', grade: 9, question: 'What is translation in biology?', options: ['Converting one language to another', 'The process of building a protein from mRNA instructions', 'Copying DNA', 'Cell movement'], answer: 1 },
    { id: 73, subject: 'Biology', grade: 10, question: 'What is the central dogma of molecular biology?', options: ['Proteins make DNA', 'DNA is transcribed to RNA, which is translated to protein', 'RNA makes DNA', 'Proteins make RNA'], answer: 1 },
    { id: 74, subject: 'Biology', grade: 10, question: 'What is a codon?', options: ['A single nucleotide', 'A sequence of three mRNA nucleotides that codes for an amino acid', 'A type of enzyme', 'A chromosome'], answer: 1 },
    { id: 75, subject: 'Biology', grade: 8, question: 'What is a genotype?', options: ['The physical appearance of an organism', 'The genetic makeup of an organism', 'A type of cell', 'An environmental factor'], answer: 1 }
  ],
  [
    { id: 76, subject: 'Biology', grade: 4, question: 'Which part of a plant carries water from the roots to the leaves?', options: ['Flower', 'Stem', 'Leaf', 'Seed'], answer: 1 },
    { id: 77, subject: 'Biology', grade: 4, question: 'What do mammals feed their babies?', options: ['Seeds', 'Milk', 'Water', 'Nectar'], answer: 1 },
    { id: 78, subject: 'Biology', grade: 5, question: 'Which organ filters blood and removes waste as urine?', options: ['Liver', 'Heart', 'Kidney', 'Lung'], answer: 2 },
    { id: 79, subject: 'Biology', grade: 5, question: 'What is germination?', options: ['When a flower blooms', 'When a seed starts to grow', 'When a leaf falls', 'When fruit ripens'], answer: 1 },
    { id: 80, subject: 'Biology', grade: 6, question: 'What is the function of the vacuole in a plant cell?', options: ['Produces energy', 'Stores water, nutrients, and waste', 'Makes proteins', 'Controls the cell'], answer: 1 },
    { id: 81, subject: 'Biology', grade: 6, question: 'What is a biome?', options: ['A single animal', 'A large region with a specific climate and organisms', 'A type of cell', 'A small pond'], answer: 1 },
    { id: 82, subject: 'Biology', grade: 7, question: 'What is osmosis?', options: ['Movement of any molecule across a membrane', 'Movement of water across a semipermeable membrane from low to high solute concentration', 'Active transport of ions', 'Diffusion of oxygen'], answer: 1 },
    { id: 83, subject: 'Biology', grade: 7, question: 'What is diffusion?', options: ['Movement of molecules from low to high concentration', 'Movement of molecules from high to low concentration', 'Only occurs in liquids', 'Requires energy'], answer: 1 },
    { id: 84, subject: 'Biology', grade: 8, question: 'What is a phenotype?', options: ['The genetic code', 'The observable characteristics of an organism', 'A type of protein', 'A chromosome number'], answer: 1 },
    { id: 85, subject: 'Biology', grade: 8, question: 'How many chromosomes do human body cells have?', options: ['23', '44', '46', '48'], answer: 2 },
    { id: 86, subject: 'Biology', grade: 9, question: 'What are lipids?', options: ['Sugars', 'Fats, oils, and waxes that store energy and form cell membranes', 'Proteins', 'Nucleic acids'], answer: 1 },
    { id: 87, subject: 'Biology', grade: 9, question: 'What is the structure of DNA?', options: ['Single strand', 'Double helix', 'Triple helix', 'Circular ring only'], answer: 1 },
    { id: 88, subject: 'Biology', grade: 10, question: 'What is an anticodon?', options: ['A codon on DNA', 'A sequence of three tRNA nucleotides complementary to an mRNA codon', 'A stop signal', 'A type of mutation'], answer: 1 },
    { id: 89, subject: 'Biology', grade: 10, question: 'What is the induced fit model of enzyme action?', options: ['The enzyme is rigid', 'The enzyme changes shape slightly to better fit the substrate', 'The substrate changes permanently', 'Enzymes do not change'], answer: 1 },
    { id: 90, subject: 'Biology', grade: 9, question: 'What is an ecosystem niche?', options: ['A hiding spot', 'The role an organism plays in its ecosystem', 'A type of habitat', 'A food source'], answer: 1 }
  ],
  [
    { id: 91, subject: 'Biology', grade: 4, question: 'Which of these is an insect?', options: ['Spider', 'Ant', 'Scorpion', 'Crab'], answer: 1 },
    { id: 92, subject: 'Biology', grade: 4, question: 'Where do desert animals typically live?', options: ['In cold wet areas', 'In hot dry areas', 'In the ocean', 'In the Arctic'], answer: 1 },
    { id: 93, subject: 'Biology', grade: 5, question: 'What is the function of the muscular system?', options: ['To think', 'To move the body', 'To digest food', 'To circulate blood'], answer: 1 },
    { id: 94, subject: 'Biology', grade: 5, question: 'Which part of the body controls all other body functions?', options: ['Heart', 'Lungs', 'Brain', 'Stomach'], answer: 2 },
    { id: 95, subject: 'Biology', grade: 6, question: 'Which level of a food chain has the most energy?', options: ['Top predators', 'Secondary consumers', 'Primary consumers', 'Producers'], answer: 3 },
    { id: 96, subject: 'Biology', grade: 6, question: 'What is the difference between a vertebrate and an invertebrate?', options: ['Size', 'Vertebrates have a backbone; invertebrates do not', 'Color', 'Diet'], answer: 1 },
    { id: 97, subject: 'Biology', grade: 7, question: 'What is the endoplasmic reticulum?', options: ['The brain of the cell', 'A network of membranes involved in protein and lipid synthesis', 'The outer boundary of the cell', 'Where photosynthesis occurs'], answer: 1 },
    { id: 98, subject: 'Biology', grade: 7, question: 'What is the function of lysosomes?', options: ['Store water', 'Break down waste materials and cellular debris', 'Produce proteins', 'Generate energy'], answer: 1 },
    { id: 99, subject: 'Biology', grade: 8, question: 'What is a mutation?', options: ['A normal cell process', 'A change in the DNA sequence', 'A type of cell division', 'A form of reproduction'], answer: 1 },
    { id: 100, subject: 'Biology', grade: 8, question: 'Who is known as the father of genetics?', options: ['Charles Darwin', 'Gregor Mendel', 'Louis Pasteur', 'Robert Hooke'], answer: 1 },
    { id: 101, subject: 'Biology', grade: 9, question: 'What is speciation?', options: ['Extinction of a species', 'The formation of new and distinct species through evolution', 'Migration of species', 'Cloning'], answer: 1 },
    { id: 102, subject: 'Biology', grade: 9, question: 'What is genetic drift?', options: ['Planned breeding', 'Random changes in allele frequency in a population', 'Natural selection', 'Mutation only'], answer: 1 },
    { id: 103, subject: 'Biology', grade: 10, question: 'What factors affect enzyme activity?', options: ['Only temperature', 'Temperature, pH, and substrate concentration', 'Only pH', 'Only substrate concentration'], answer: 1 },
    { id: 104, subject: 'Biology', grade: 10, question: 'What happens to an enzyme at very high temperatures?', options: ['It works faster indefinitely', 'It denatures and loses its shape and function', 'It becomes stronger', 'It replicates'], answer: 1 },
    { id: 105, subject: 'Biology', grade: 10, question: 'What is the role of DNA polymerase?', options: ['It breaks down DNA', 'It synthesizes new DNA strands during replication', 'It transcribes RNA', 'It translates proteins'], answer: 1 }
  ],
  [
    { id: 106, subject: 'Biology', grade: 4, question: 'What is the main job of a leaf?', options: ['Absorb water', 'Make food for the plant', 'Hold the plant up', 'Attract bees'], answer: 1 },
    { id: 107, subject: 'Biology', grade: 4, question: 'How many legs does an insect have?', options: ['4', '6', '8', '10'], answer: 1 },
    { id: 108, subject: 'Biology', grade: 5, question: 'What are the tiny air sacs in the lungs called?', options: ['Bronchi', 'Alveoli', 'Trachea', 'Capillaries'], answer: 1 },
    { id: 109, subject: 'Biology', grade: 5, question: 'What do red blood cells carry?', options: ['Carbon dioxide only', 'Oxygen', 'White blood cells', 'Nutrients only'], answer: 1 },
    { id: 110, subject: 'Biology', grade: 6, question: 'What is the function of xylem in plants?', options: ['Transports sugar', 'Transports water from roots to leaves', 'Produces seeds', 'Absorbs light'], answer: 1 },
    { id: 111, subject: 'Biology', grade: 6, question: 'What is the function of phloem in plants?', options: ['Transports water upward', 'Transports sugar from leaves to other parts', 'Provides structure', 'Absorbs minerals'], answer: 1 },
    { id: 112, subject: 'Biology', grade: 7, question: 'What is the difference between rough and smooth endoplasmic reticulum?', options: ['Size', 'Rough ER has ribosomes attached; smooth ER does not', 'Color', 'Rough ER is in plants only'], answer: 1 },
    { id: 113, subject: 'Biology', grade: 7, question: 'What is active transport?', options: ['Movement without energy', 'Movement of molecules against their concentration gradient using energy', 'Diffusion', 'Osmosis'], answer: 1 },
    { id: 114, subject: 'Biology', grade: 8, question: 'What is heredity?', options: ['The study of ecosystems', 'The passing of traits from parents to offspring', 'A type of cell', 'The study of fossils'], answer: 1 },
    { id: 115, subject: 'Biology', grade: 8, question: 'What is a heterozygous genotype?', options: ['Two identical alleles', 'Two different alleles for a trait', 'No alleles', 'Three alleles'], answer: 1 },
    { id: 116, subject: 'Biology', grade: 9, question: 'What is gene flow?', options: ['Movement of water through genes', 'Transfer of alleles between populations through migration', 'DNA replication', 'Transcription'], answer: 1 },
    { id: 117, subject: 'Biology', grade: 9, question: 'What is the endosymbiotic theory?', options: ['Cells are not related', 'Mitochondria and chloroplasts were once independent prokaryotes engulfed by larger cells', 'All cells come from viruses', 'Eukaryotes evolved from fungi'], answer: 1 },
    { id: 118, subject: 'Biology', grade: 10, question: 'What is the role of RNA polymerase?', options: ['It replicates DNA', 'It synthesizes mRNA from a DNA template during transcription', 'It builds proteins', 'It breaks down RNA'], answer: 1 },
    { id: 119, subject: 'Biology', grade: 10, question: 'What are Okazaki fragments?', options: ['Pieces of protein', 'Short segments of DNA synthesized on the lagging strand during replication', 'RNA molecules', 'Enzyme fragments'], answer: 1 },
    { id: 120, subject: 'Biology', grade: 4, question: 'What do omnivores eat?', options: ['Only plants', 'Only meat', 'Both plants and meat', 'Only insects'], answer: 2 }
  ],
  [
    { id: 121, subject: 'Biology', grade: 4, question: 'Which animal lays eggs and has feathers?', options: ['Dog', 'Chicken', 'Cat', 'Whale'], answer: 1 },
    { id: 122, subject: 'Biology', grade: 4, question: 'What do plants release into the air during the day?', options: ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Helium'], answer: 2 },
    { id: 123, subject: 'Biology', grade: 5, question: 'Which type of teeth are used for tearing food?', options: ['Incisors', 'Canines', 'Molars', 'Premolars'], answer: 1 },
    { id: 124, subject: 'Biology', grade: 5, question: 'What is the outermost layer of a tree trunk called?', options: ['Heartwood', 'Sapwood', 'Bark', 'Cambium'], answer: 2 },
    { id: 125, subject: 'Biology', grade: 6, question: 'What is symbiosis?', options: ['Competition between species', 'A close relationship between two different species', 'A type of reproduction', 'Predator-prey interaction only'], answer: 1 },
    { id: 126, subject: 'Biology', grade: 6, question: 'What type of symbiosis benefits both organisms?', options: ['Parasitism', 'Commensalism', 'Mutualism', 'Competition'], answer: 2 },
    { id: 127, subject: 'Biology', grade: 7, question: 'What are the products of cellular respiration?', options: ['Glucose and oxygen', 'Carbon dioxide, water, and ATP', 'Only carbon dioxide', 'Only water'], answer: 1 },
    { id: 128, subject: 'Biology', grade: 7, question: 'What is the function of the cytoplasm?', options: ['Contains DNA', 'Gel-like substance that holds organelles in place', 'Produces energy', 'Forms the cell wall'], answer: 1 },
    { id: 129, subject: 'Biology', grade: 8, question: 'What is a homozygous genotype?', options: ['Two different alleles', 'Two identical alleles for a trait', 'Only one allele', 'No alleles present'], answer: 1 },
    { id: 130, subject: 'Biology', grade: 8, question: 'What are sex chromosomes?', options: ['Chromosomes that determine blood type', 'Chromosomes that determine biological sex (XX or XY)', 'Chromosomes found only in plants', 'Chromosomes that code for eye color only'], answer: 1 },
    { id: 131, subject: 'Biology', grade: 9, question: 'What is ATP?', options: ['A vitamin', 'Adenosine triphosphate, the main energy currency of cells', 'A type of DNA', 'A hormone'], answer: 1 },
    { id: 132, subject: 'Biology', grade: 9, question: 'What is the difference between aerobic and anaerobic respiration?', options: ['They are the same', 'Aerobic requires oxygen; anaerobic does not', 'Anaerobic requires oxygen', 'Aerobic does not produce ATP'], answer: 1 },
    { id: 133, subject: 'Biology', grade: 10, question: 'What is the difference between a leading and lagging strand in DNA replication?', options: ['They are the same', 'The leading strand is synthesized continuously; the lagging strand in fragments', 'The lagging strand is faster', 'Only the leading strand is copied'], answer: 1 },
    { id: 134, subject: 'Biology', grade: 10, question: 'What is a point mutation?', options: ['A large chromosome deletion', 'A change in a single nucleotide in the DNA sequence', 'Adding an entire chromosome', 'Losing an entire chromosome'], answer: 1 },
    { id: 135, subject: 'Biology', grade: 5, question: 'Which part of the digestive system absorbs most nutrients?', options: ['Stomach', 'Small intestine', 'Large intestine', 'Esophagus'], answer: 1 }
  ],
  [
    { id: 136, subject: 'Biology', grade: 4, question: 'Which body part helps you hear sounds?', options: ['Eye', 'Ear', 'Nose', 'Tongue'], answer: 1 },
    { id: 137, subject: 'Biology', grade: 4, question: 'What is a baby frog called?', options: ['Cub', 'Tadpole', 'Larva', 'Pup'], answer: 1 },
    { id: 138, subject: 'Biology', grade: 5, question: 'What is the function of the nose besides smelling?', options: ['Tasting food', 'Filtering and warming air', 'Hearing sounds', 'Seeing colors'], answer: 1 },
    { id: 139, subject: 'Biology', grade: 5, question: 'What do we call animals that are active at night?', options: ['Diurnal', 'Nocturnal', 'Hibernating', 'Migrating'], answer: 1 },
    { id: 140, subject: 'Biology', grade: 6, question: 'What is the water cycle in relation to ecosystems?', options: ['Water only exists in oceans', 'The continuous movement of water through evaporation, condensation, and precipitation', 'Water is created by plants', 'Water never changes form'], answer: 1 },
    { id: 141, subject: 'Biology', grade: 6, question: 'Which kingdom includes mushrooms and mold?', options: ['Plantae', 'Animalia', 'Fungi', 'Protista'], answer: 2 },
    { id: 142, subject: 'Biology', grade: 7, question: 'What is a tissue in biology?', options: ['A single cell', 'A group of similar cells working together', 'An organ system', 'An organism'], answer: 1 },
    { id: 143, subject: 'Biology', grade: 7, question: 'What is the correct order of organization in living things?', options: ['Organ, tissue, cell, organ system', 'Cell, tissue, organ, organ system', 'Tissue, cell, organ system, organ', 'Organ system, organ, cell, tissue'], answer: 1 },
    { id: 144, subject: 'Biology', grade: 8, question: 'What is incomplete dominance?', options: ['One allele completely masks the other', 'The heterozygous phenotype is a blend of both alleles', 'Both alleles are fully expressed', 'Neither allele is expressed'], answer: 1 },
    { id: 145, subject: 'Biology', grade: 8, question: 'What is codominance?', options: ['One allele masks the other', 'Both alleles are fully and separately expressed in the phenotype', 'A blend of traits', 'Neither allele works'], answer: 1 },
    { id: 146, subject: 'Biology', grade: 9, question: 'What are the stages of cellular respiration?', options: ['Only glycolysis', 'Glycolysis, Krebs cycle, and electron transport chain', 'Only the Krebs cycle', 'Photosynthesis and glycolysis'], answer: 1 },
    { id: 147, subject: 'Biology', grade: 9, question: 'What is the Calvin cycle?', options: ['A cycling race', 'The light-independent reactions of photosynthesis that fix carbon dioxide into glucose', 'Cellular respiration', 'DNA replication'], answer: 1 },
    { id: 148, subject: 'Biology', grade: 10, question: 'What is a frameshift mutation?', options: ['A silent mutation', 'An insertion or deletion of nucleotides that shifts the reading frame of codons', 'A point mutation', 'A beneficial mutation always'], answer: 1 },
    { id: 149, subject: 'Biology', grade: 10, question: 'What is gel electrophoresis used for?', options: ['Cooking food', 'Separating DNA fragments by size', 'Viewing cells', 'Measuring temperature'], answer: 1 },
    { id: 150, subject: 'Biology', grade: 6, question: 'What is the main difference between bacteria and viruses?', options: ['Bacteria are smaller', 'Bacteria are living cells; viruses are not considered living', 'Viruses are larger', 'There is no difference'], answer: 1 }
  ],
  [
    { id: 151, subject: 'Biology', grade: 4, question: 'Which of these animals lives in water?', options: ['Eagle', 'Lion', 'Dolphin', 'Deer'], answer: 2 },
    { id: 152, subject: 'Biology', grade: 4, question: 'What do roots do for a plant?', options: ['Make food', 'Absorb water and anchor the plant', 'Attract insects', 'Produce seeds'], answer: 1 },
    { id: 153, subject: 'Biology', grade: 5, question: 'What is the lifespan order of a butterfly?', options: ['Egg, larva, pupa, adult', 'Egg, pupa, larva, adult', 'Adult, egg, larva, pupa', 'Larva, egg, adult, pupa'], answer: 0 },
    { id: 154, subject: 'Biology', grade: 5, question: 'Which is the correct food chain?', options: ['Fox eats grass, rabbit eats fox', 'Grass grows, rabbit eats grass, fox eats rabbit', 'Rabbit eats fox, fox eats grass', 'Fox eats grass, grass eats rabbit'], answer: 1 },
    { id: 155, subject: 'Biology', grade: 6, question: 'What is camouflage?', options: ['A type of food', 'An adaptation that helps organisms blend in with their environment', 'A disease', 'A type of reproduction'], answer: 1 },
    { id: 156, subject: 'Biology', grade: 6, question: 'What does endangered species mean?', options: ['A species that is very common', 'A species at risk of extinction', 'A species that is already extinct', 'A new species'], answer: 1 },
    { id: 157, subject: 'Biology', grade: 7, question: 'What is the function of the nervous system?', options: ['To transport nutrients', 'To send electrical signals and coordinate body functions', 'To filter blood', 'To produce hormones only'], answer: 1 },
    { id: 158, subject: 'Biology', grade: 7, question: 'What is the trachea?', options: ['A blood vessel', 'The windpipe that carries air to the lungs', 'A digestive organ', 'A type of muscle'], answer: 1 },
    { id: 159, subject: 'Biology', grade: 8, question: 'What is selective breeding?', options: ['Natural selection in the wild', 'Humans choosing organisms with desired traits to breed', 'Random mating', 'Cloning organisms'], answer: 1 },
    { id: 160, subject: 'Biology', grade: 8, question: 'What is the function of the endocrine system?', options: ['To digest food', 'To produce hormones that regulate body functions', 'To transport oxygen', 'To remove waste'], answer: 1 },
    { id: 161, subject: 'Biology', grade: 9, question: 'What are the light-dependent reactions of photosynthesis?', options: ['Reactions that occur in the dark', 'Reactions in the thylakoid membranes that use light to produce ATP and NADPH', 'Reactions that break down glucose', 'Reactions that occur in the cytoplasm'], answer: 1 },
    { id: 162, subject: 'Biology', grade: 9, question: 'What is biodiversity?', options: ['Having one species', 'The variety of life in a particular habitat or ecosystem', 'A type of pollution', 'A single biome'], answer: 1 },
    { id: 163, subject: 'Biology', grade: 10, question: 'What is PCR (polymerase chain reaction)?', options: ['A disease', 'A technique to amplify specific DNA sequences', 'A type of cell division', 'A protein synthesis method'], answer: 1 },
    { id: 164, subject: 'Biology', grade: 10, question: 'What is genetic engineering?', options: ['Building machines', 'Direct manipulation of an organism\'s genes using biotechnology', 'Natural selection', 'Selective breeding only'], answer: 1 },
    { id: 165, subject: 'Biology', grade: 7, question: 'What is the diaphragm?', options: ['A bone', 'A muscle that helps with breathing', 'A type of blood cell', 'Part of the brain'], answer: 1 }
  ],
  [
    { id: 166, subject: 'Biology', grade: 4, question: 'Which of these is a mammal?', options: ['Frog', 'Snake', 'Whale', 'Goldfish'], answer: 2 },
    { id: 167, subject: 'Biology', grade: 4, question: 'What happens to most trees in autumn?', options: ['They grow taller', 'Their leaves change color and fall', 'They produce fruit', 'They stop needing water'], answer: 1 },
    { id: 168, subject: 'Biology', grade: 5, question: 'What is the main function of the large intestine?', options: ['Digest proteins', 'Absorb water from waste', 'Produce bile', 'Break down fats'], answer: 1 },
    { id: 169, subject: 'Biology', grade: 5, question: 'What protects the brain inside the head?', options: ['Skin only', 'The skull', 'Muscles only', 'Hair'], answer: 1 },
    { id: 170, subject: 'Biology', grade: 6, question: 'What is the carbon cycle?', options: ['Carbon only exists in coal', 'The movement of carbon through living things, atmosphere, oceans, and earth', 'Carbon is only in the air', 'Carbon does not cycle'], answer: 1 },
    { id: 171, subject: 'Biology', grade: 6, question: 'What happens to energy as it moves up a food chain?', options: ['It increases', 'It stays the same', 'It decreases', 'It disappears completely'], answer: 2 },
    { id: 172, subject: 'Biology', grade: 7, question: 'What is homeostasis?', options: ['The study of homes', 'The maintenance of a stable internal environment', 'A type of cell division', 'A disease'], answer: 1 },
    { id: 173, subject: 'Biology', grade: 7, question: 'What is the pH scale used to measure?', options: ['Temperature', 'How acidic or basic a solution is', 'Weight', 'Length'], answer: 1 },
    { id: 174, subject: 'Biology', grade: 8, question: 'What is the immune system?', options: ['The skeletal system', 'The body defense system against pathogens', 'The digestive system', 'The nervous system'], answer: 1 },
    { id: 175, subject: 'Biology', grade: 8, question: 'What are antibodies?', options: ['A type of pathogen', 'Proteins produced by the immune system to fight infections', 'Red blood cells', 'Hormones'], answer: 1 },
    { id: 176, subject: 'Biology', grade: 9, question: 'What is a keystone species?', options: ['The most common species', 'A species that has a disproportionately large effect on its ecosystem', 'The largest animal', 'An extinct species'], answer: 1 },
    { id: 177, subject: 'Biology', grade: 9, question: 'What is succession in ecology?', options: ['A type of mutation', 'The gradual process of change in species composition in an ecosystem over time', 'Extinction', 'Migration'], answer: 1 },
    { id: 178, subject: 'Biology', grade: 10, question: 'What are restriction enzymes?', options: ['Enzymes that build DNA', 'Enzymes that cut DNA at specific recognition sequences', 'Enzymes that repair proteins', 'Enzymes in the stomach'], answer: 1 },
    { id: 179, subject: 'Biology', grade: 10, question: 'What is a plasmid?', options: ['A type of virus', 'A small circular DNA molecule found in bacteria, often used in genetic engineering', 'A cell organelle', 'A type of protein'], answer: 1 },
    { id: 180, subject: 'Biology', grade: 8, question: 'What is a vaccine?', options: ['A cure for all diseases', 'A weakened or inactive form of a pathogen that stimulates immunity', 'A type of antibiotic', 'A vitamin supplement'], answer: 1 }
  ],
  [
    { id: 181, subject: 'Biology', grade: 4, question: 'What is the skeleton made of?', options: ['Muscles', 'Bones', 'Skin', 'Blood'], answer: 1 },
    { id: 182, subject: 'Biology', grade: 4, question: 'Which animal undergoes metamorphosis?', options: ['Dog', 'Butterfly', 'Cow', 'Horse'], answer: 1 },
    { id: 183, subject: 'Biology', grade: 5, question: 'What happens during hibernation?', options: ['Animals move to warmer places', 'Animals sleep through cold months to save energy', 'Animals shed their fur', 'Animals lay eggs'], answer: 1 },
    { id: 184, subject: 'Biology', grade: 5, question: 'What is migration?', options: ['Animals sleeping through winter', 'Animals moving to a new location seasonally', 'Animals changing color', 'Animals shedding skin'], answer: 1 },
    { id: 185, subject: 'Biology', grade: 6, question: 'What is an adaptation?', options: ['A learned behavior only', 'A trait that helps an organism survive in its environment', 'A type of food', 'A disease'], answer: 1 },
    { id: 186, subject: 'Biology', grade: 6, question: 'What is the nitrogen cycle?', options: ['Nitrogen only exists in the air', 'The process by which nitrogen is converted between various chemical forms in the environment', 'Nitrogen is only in water', 'Plants produce all nitrogen'], answer: 1 },
    { id: 187, subject: 'Biology', grade: 7, question: 'What type of microscope uses lenses to magnify objects?', options: ['Electron microscope', 'Light microscope', 'X-ray machine', 'Telescope'], answer: 1 },
    { id: 188, subject: 'Biology', grade: 7, question: 'What is the function of tendons?', options: ['Connect bones to bones', 'Connect muscles to bones', 'Carry blood', 'Transmit nerve signals'], answer: 1 },
    { id: 189, subject: 'Biology', grade: 8, question: 'What is the difference between a virus and a bacterium?', options: ['They are the same', 'Bacteria are single-celled organisms; viruses need a host cell to reproduce', 'Viruses are larger', 'Bacteria are not alive'], answer: 1 },
    { id: 190, subject: 'Biology', grade: 8, question: 'What is asexual reproduction?', options: ['Reproduction requiring two parents', 'Reproduction from a single parent producing genetically identical offspring', 'Sexual reproduction in plants', 'Reproduction only in bacteria'], answer: 1 },
    { id: 191, subject: 'Biology', grade: 9, question: 'What is the difference between primary and secondary succession?', options: ['They are the same', 'Primary starts on bare rock; secondary starts where a community was disturbed', 'Primary is faster', 'Secondary starts on bare rock'], answer: 1 },
    { id: 192, subject: 'Biology', grade: 9, question: 'What is a trophic level?', options: ['A type of disease', 'A feeding level in a food chain or food web', 'A cell organelle', 'A type of biome'], answer: 1 },
    { id: 193, subject: 'Biology', grade: 10, question: 'What is apoptosis?', options: ['Cell growth', 'Programmed cell death', 'Cell division', 'Cell movement'], answer: 1 },
    { id: 194, subject: 'Biology', grade: 10, question: 'What are tumor suppressor genes?', options: ['Genes that cause cancer', 'Genes that regulate cell division and prevent uncontrolled growth', 'Genes for eye color', 'Genes only in plants'], answer: 1 },
    { id: 195, subject: 'Biology', grade: 9, question: 'What is biomagnification?', options: ['Making organisms larger', 'The increasing concentration of toxins in organisms at higher trophic levels', 'A type of microscope', 'Cell growth'], answer: 1 }
  ],
  [
    { id: 196, subject: 'Biology', grade: 4, question: 'What is the hard outer covering of an insect called?', options: ['Shell', 'Exoskeleton', 'Skin', 'Fur'], answer: 1 },
    { id: 197, subject: 'Biology', grade: 4, question: 'What type of animal lives both on land and in water?', options: ['Reptile', 'Amphibian', 'Mammal', 'Bird'], answer: 1 },
    { id: 198, subject: 'Biology', grade: 5, question: 'What is the main function of the stomach?', options: ['To pump blood', 'To break down food with acid and enzymes', 'To filter air', 'To send signals to the brain'], answer: 1 },
    { id: 199, subject: 'Biology', grade: 5, question: 'What are the stages of the human life cycle?', options: ['Baby, child, teenager, adult, elderly', 'Egg, larva, pupa, adult', 'Seed, sprout, plant', 'Birth and death only'], answer: 0 },
    { id: 200, subject: 'Biology', grade: 6, question: 'What is parasitism?', options: ['Both organisms benefit', 'One organism benefits while the other is harmed', 'Both organisms are harmed', 'Neither organism is affected'], answer: 1 },
    { id: 201, subject: 'Biology', grade: 6, question: 'What is commensalism?', options: ['Both organisms benefit', 'One organism benefits and the other is unaffected', 'Both organisms are harmed', 'One organism is harmed'], answer: 1 },
    { id: 202, subject: 'Biology', grade: 7, question: 'What is the role of the nucleus in a cell?', options: ['Energy production', 'It stores DNA and controls cell activities', 'It digests food', 'It provides structure'], answer: 1 },
    { id: 203, subject: 'Biology', grade: 7, question: 'What are chromosomes?', options: ['A type of cell', 'Structures made of DNA and protein that carry genetic information', 'Energy molecules', 'Cell membranes'], answer: 1 },
    { id: 204, subject: 'Biology', grade: 8, question: 'What is the law of segregation?', options: ['Organisms must stay separate', 'During gamete formation, the two alleles for a gene separate so each gamete carries only one allele', 'Cells never divide', 'DNA does not replicate'], answer: 1 },
    { id: 205, subject: 'Biology', grade: 8, question: 'What is the law of independent assortment?', options: ['All genes are linked', 'Genes on different chromosomes are inherited independently of each other', 'Genes always travel together', 'Only one gene is inherited'], answer: 1 },
    { id: 206, subject: 'Biology', grade: 9, question: 'What is the difference between saturated and unsaturated fats?', options: ['They are the same', 'Saturated fats have no double bonds between carbons; unsaturated have one or more', 'Unsaturated fats are solid at room temperature', 'Saturated fats are always liquid'], answer: 1 },
    { id: 207, subject: 'Biology', grade: 9, question: 'What is a peptide bond?', options: ['A bond between sugars', 'A covalent bond between amino acids in a protein', 'A bond in DNA', 'A hydrogen bond'], answer: 1 },
    { id: 208, subject: 'Biology', grade: 10, question: 'What are oncogenes?', options: ['Normal genes that help cells grow', 'Mutated genes that can lead to uncontrolled cell division and cancer', 'Genes that suppress tumors', 'Genes for blood type'], answer: 1 },
    { id: 209, subject: 'Biology', grade: 10, question: 'What is the Hardy-Weinberg equilibrium?', options: ['A chemistry concept', 'A principle stating allele frequencies remain constant when no evolutionary forces act', 'A type of ecosystem', 'A cell cycle phase'], answer: 1 },
    { id: 210, subject: 'Biology', grade: 10, question: 'What is cladistics?', options: ['A type of disease', 'A method of classifying organisms based on shared derived characteristics and evolutionary relationships', 'A cell process', 'A type of mutation'], answer: 1 }
  ],
  [
    { id: 211, subject: 'Biology', grade: 4, question: 'Which part of a flower attracts pollinators with color?', options: ['Stem', 'Petals', 'Roots', 'Thorns'], answer: 1 },
    { id: 212, subject: 'Biology', grade: 4, question: 'What do animals need to survive?', options: ['Only water', 'Food, water, air, and shelter', 'Only food', 'Only sunlight'], answer: 1 },
    { id: 213, subject: 'Biology', grade: 5, question: 'What is the esophagus?', options: ['A bone', 'The tube connecting the mouth to the stomach', 'A type of muscle', 'Part of the lungs'], answer: 1 },
    { id: 214, subject: 'Biology', grade: 5, question: 'What is the function of saliva?', options: ['Only to keep the mouth wet', 'To begin breaking down food and moisten it for swallowing', 'To fight infections', 'To help you taste food only'], answer: 1 },
    { id: 215, subject: 'Biology', grade: 6, question: 'What is the difference between a population and a community?', options: ['They are the same', 'A population is one species in an area; a community is all species in an area', 'A community is one species', 'A population includes non-living things'], answer: 1 },
    { id: 216, subject: 'Biology', grade: 6, question: 'What is a limiting factor in an ecosystem?', options: ['Something that has no effect', 'A factor that restricts the size of a population', 'A type of organism', 'An unlimited resource'], answer: 1 },
    { id: 217, subject: 'Biology', grade: 7, question: 'What is the cell cycle?', options: ['Only mitosis', 'The series of events in the life of a cell including growth and division', 'Cell death only', 'Movement of cells'], answer: 1 },
    { id: 218, subject: 'Biology', grade: 7, question: 'What is interphase?', options: ['Cell division', 'The phase where the cell grows, copies DNA, and prepares for division', 'Cell death', 'When cells stop working'], answer: 1 },
    { id: 219, subject: 'Biology', grade: 8, question: 'What is a carrier in genetics?', options: ['Someone who is sick', 'An individual who has one copy of a recessive allele but does not show the trait', 'A dominant individual', 'A mutant'], answer: 1 },
    { id: 220, subject: 'Biology', grade: 8, question: 'What is sickle cell anemia?', options: ['A bone disease', 'A genetic blood disorder where red blood cells become sickle-shaped', 'A type of cancer', 'An infection'], answer: 1 },
    { id: 221, subject: 'Biology', grade: 9, question: 'What are the levels of protein structure?', options: ['Only primary', 'Primary, secondary, tertiary, and quaternary', 'Only tertiary', 'Primary and secondary only'], answer: 1 },
    { id: 222, subject: 'Biology', grade: 9, question: 'What is denaturation of a protein?', options: ['Making a protein stronger', 'The loss of a protein\'s three-dimensional structure and function', 'Protein synthesis', 'Protein digestion'], answer: 1 },
    { id: 223, subject: 'Biology', grade: 10, question: 'What is epigenetics?', options: ['A type of mutation', 'The study of changes in gene expression that do not involve changes to the DNA sequence', 'A branch of ecology', 'A type of cell division'], answer: 1 },
    { id: 224, subject: 'Biology', grade: 10, question: 'What is CRISPR-Cas9?', options: ['A type of microscope', 'A gene-editing tool that allows precise modifications to DNA', 'A type of cell', 'A protein structure'], answer: 1 },
    { id: 225, subject: 'Biology', grade: 4, question: 'What is the life cycle of a plant?', options: ['Seed, sprout, mature plant, flower, fruit, seed', 'Egg, larva, pupa, adult', 'Birth, growth, death only', 'There is no cycle'], answer: 0 }
  ],
  [
    { id: 226, subject: 'Biology', grade: 4, question: 'Which animal has a pouch for carrying babies?', options: ['Dog', 'Kangaroo', 'Fish', 'Bird'], answer: 1 },
    { id: 227, subject: 'Biology', grade: 4, question: 'What is the job of the heart?', options: ['To think', 'To pump blood', 'To breathe', 'To digest food'], answer: 1 },
    { id: 228, subject: 'Biology', grade: 5, question: 'What is an inherited trait?', options: ['A trait you learn at school', 'A trait passed from parents to offspring through genes', 'A trait from eating healthy', 'A trait from exercise'], answer: 1 },
    { id: 229, subject: 'Biology', grade: 5, question: 'What is a learned behavior?', options: ['A behavior you are born with', 'A behavior gained through experience or teaching', 'An instinct', 'A reflex'], answer: 1 },
    { id: 230, subject: 'Biology', grade: 6, question: 'What is carrying capacity?', options: ['How much an animal can carry', 'The maximum population size an environment can sustain', 'A type of habitat', 'The weight of an ecosystem'], answer: 1 },
    { id: 231, subject: 'Biology', grade: 6, question: 'What is the difference between biotic and abiotic factors?', options: ['They are the same', 'Biotic factors are living; abiotic factors are non-living', 'Abiotic means living', 'Biotic means non-living'], answer: 1 },
    { id: 232, subject: 'Biology', grade: 7, question: 'What is cytokinesis?', options: ['DNA replication', 'The division of the cytoplasm to form two separate cells', 'Protein synthesis', 'Cell growth'], answer: 1 },
    { id: 233, subject: 'Biology', grade: 7, question: 'What are stem cells?', options: ['Plant stems', 'Undifferentiated cells that can develop into specialized cell types', 'Dead cells', 'Cancer cells'], answer: 1 },
    { id: 234, subject: 'Biology', grade: 8, question: 'What is the role of insulin?', options: ['To digest protein', 'To regulate blood sugar levels by allowing cells to take in glucose', 'To fight infections', 'To carry oxygen'], answer: 1 },
    { id: 235, subject: 'Biology', grade: 8, question: 'What is a karyotype?', options: ['A type of cell', 'An organized display of an organism\'s chromosomes', 'A genetic disease', 'A type of allele'], answer: 1 },
    { id: 236, subject: 'Biology', grade: 9, question: 'What is the function of cholesterol in cell membranes?', options: ['It destroys the membrane', 'It helps maintain membrane fluidity and stability', 'It provides energy', 'It stores genetic information'], answer: 1 },
    { id: 237, subject: 'Biology', grade: 9, question: 'What is the fluid mosaic model?', options: ['A type of painting', 'A model describing the cell membrane as a flexible structure with proteins embedded in a lipid bilayer', 'A type of ecosystem', 'A DNA model'], answer: 1 },
    { id: 238, subject: 'Biology', grade: 10, question: 'What is a transgenic organism?', options: ['An organism with no genes', 'An organism that contains genes from another species', 'A cloned organism', 'An extinct species'], answer: 1 },
    { id: 239, subject: 'Biology', grade: 10, question: 'What is the role of helicase in DNA replication?', options: ['It joins DNA strands', 'It unwinds and separates the two DNA strands', 'It adds nucleotides', 'It proofreads DNA'], answer: 1 },
    { id: 240, subject: 'Biology', grade: 5, question: 'What is the function of the liver?', options: ['To pump blood', 'To process nutrients, filter blood, and produce bile', 'To breathe', 'To move the body'], answer: 1 }
  ],
  [
    { id: 241, subject: 'Biology', grade: 4, question: 'What type of animal has fur or hair?', options: ['Fish', 'Reptile', 'Mammal', 'Amphibian'], answer: 2 },
    { id: 242, subject: 'Biology', grade: 4, question: 'What are the five senses?', options: ['Running, jumping, swimming, climbing, flying', 'Sight, hearing, smell, taste, touch', 'Eating, sleeping, breathing, growing, moving', 'Thinking, feeling, dreaming, hoping, wishing'], answer: 1 },
    { id: 243, subject: 'Biology', grade: 5, question: 'How does a cactus survive in the desert?', options: ['It needs lots of water', 'It stores water in its thick stem and has spines to reduce water loss', 'It has large leaves', 'It only grows at night'], answer: 1 },
    { id: 244, subject: 'Biology', grade: 5, question: 'What is the food chain in a pond ecosystem?', options: ['Only big fish', 'Algae, small insects, small fish, large fish', 'Only plants', 'Only bacteria'], answer: 1 },
    { id: 245, subject: 'Biology', grade: 6, question: 'What is a producer in an ecosystem?', options: ['An animal that eats meat', 'An organism that makes its own food through photosynthesis', 'A decomposer', 'A consumer'], answer: 1 },
    { id: 246, subject: 'Biology', grade: 6, question: 'What is the role of fungi in an ecosystem?', options: ['They photosynthesize', 'They decompose dead organic matter and recycle nutrients', 'They produce oxygen', 'They eat animals'], answer: 1 },
    { id: 247, subject: 'Biology', grade: 7, question: 'What is the function of platelets?', options: ['Fight infections', 'Help blood clot at wound sites', 'Carry oxygen', 'Produce antibodies'], answer: 1 },
    { id: 248, subject: 'Biology', grade: 7, question: 'What are the major types of blood vessels?', options: ['Only veins', 'Arteries, veins, and capillaries', 'Only arteries', 'Only capillaries'], answer: 1 },
    { id: 249, subject: 'Biology', grade: 8, question: 'What is Down syndrome caused by?', options: ['A missing chromosome', 'An extra copy of chromosome 21', 'A virus', 'A bacterial infection'], answer: 1 },
    { id: 250, subject: 'Biology', grade: 8, question: 'What are sex-linked traits?', options: ['Traits on any chromosome', 'Traits determined by genes on the sex chromosomes', 'Traits that determine sex only', 'Traits not affected by genes'], answer: 1 },
    { id: 251, subject: 'Biology', grade: 9, question: 'What is chemiosmosis?', options: ['Osmosis of chemicals', 'The movement of ions across a membrane to drive ATP synthesis', 'A type of diffusion', 'Cell division'], answer: 1 },
    { id: 252, subject: 'Biology', grade: 9, question: 'What is NADPH?', options: ['A type of DNA', 'An electron carrier used in the Calvin cycle of photosynthesis', 'A protein', 'An enzyme'], answer: 1 },
    { id: 253, subject: 'Biology', grade: 10, question: 'What is a promoter region in DNA?', options: ['A region that codes for protein', 'A sequence where RNA polymerase binds to begin transcription', 'The end of a gene', 'A repetitive sequence'], answer: 1 },
    { id: 254, subject: 'Biology', grade: 10, question: 'What is alternative splicing?', options: ['Cutting DNA', 'A process where one gene can produce multiple different mRNA molecules and proteins', 'Joining chromosomes', 'Breaking down RNA'], answer: 1 },
    { id: 255, subject: 'Biology', grade: 6, question: 'What is the relationship between predator and prey?', options: ['They help each other', 'The predator hunts and eats the prey', 'They compete for the same food', 'They ignore each other'], answer: 1 }
  ],
  [
    { id: 256, subject: 'Biology', grade: 4, question: 'What part of the body helps you breathe?', options: ['Stomach', 'Lungs', 'Liver', 'Kidneys'], answer: 1 },
    { id: 257, subject: 'Biology', grade: 4, question: 'What is the purpose of a flower on a plant?', options: ['To look pretty only', 'To help in reproduction by attracting pollinators', 'To absorb water', 'To store food'], answer: 1 },
    { id: 258, subject: 'Biology', grade: 5, question: 'What is a parasite?', options: ['A helpful organism', 'An organism that lives on or in another organism and harms it', 'A type of plant', 'A decomposer'], answer: 1 },
    { id: 259, subject: 'Biology', grade: 5, question: 'What is the purpose of bark on a tree?', options: ['To look nice', 'To protect the tree from damage, disease, and water loss', 'To absorb sunlight', 'To produce seeds'], answer: 1 },
    { id: 260, subject: 'Biology', grade: 6, question: 'What is a wetland?', options: ['A dry desert', 'An area where land is saturated with water, supporting unique ecosystems', 'A mountain top', 'An ocean floor'], answer: 1 },
    { id: 261, subject: 'Biology', grade: 6, question: 'What is a coral reef?', options: ['A type of rock', 'An underwater ecosystem built by colonies of tiny coral animals', 'A sandy beach', 'A deep ocean trench'], answer: 1 },
    { id: 262, subject: 'Biology', grade: 7, question: 'What is the function of the small intestine?', options: ['Store waste', 'Absorb nutrients from digested food into the bloodstream', 'Produce bile', 'Filter blood'], answer: 1 },
    { id: 263, subject: 'Biology', grade: 7, question: 'What is the function of villi in the small intestine?', options: ['Produce enzymes only', 'Increase surface area for nutrient absorption', 'Move food along', 'Store vitamins'], answer: 1 },
    { id: 264, subject: 'Biology', grade: 8, question: 'What is a pedigree chart?', options: ['A dog breed chart', 'A diagram showing the inheritance of a trait through generations of a family', 'A food chain', 'A cell diagram'], answer: 1 },
    { id: 265, subject: 'Biology', grade: 8, question: 'What is genetic variation?', options: ['All organisms being identical', 'Differences in DNA sequences among individuals in a population', 'A type of mutation only', 'Cloning'], answer: 1 },
    { id: 266, subject: 'Biology', grade: 9, question: 'What is the role of oxygen in cellular respiration?', options: ['It is not needed', 'It is the final electron acceptor in the electron transport chain', 'It is a waste product', 'It starts glycolysis'], answer: 1 },
    { id: 267, subject: 'Biology', grade: 9, question: 'What is an invasive species?', options: ['A native species', 'A non-native species that causes harm to the ecosystem it is introduced to', 'Any large animal', 'A beneficial organism'], answer: 1 },
    { id: 268, subject: 'Biology', grade: 10, question: 'What is a stop codon?', options: ['A codon that starts translation', 'A codon that signals the end of translation (UAA, UAG, UGA)', 'A codon for amino acids', 'A codon in DNA only'], answer: 1 },
    { id: 269, subject: 'Biology', grade: 10, question: 'What is the start codon?', options: ['UAA', 'AUG, which codes for methionine', 'UGA', 'UAG'], answer: 1 },
    { id: 270, subject: 'Biology', grade: 7, question: 'What is the function of the gallbladder?', options: ['Produces insulin', 'Stores and releases bile to help digest fats', 'Filters blood', 'Produces hormones'], answer: 1 }
  ],
  [
    { id: 271, subject: 'Biology', grade: 4, question: 'Which of these is a predator?', options: ['Rabbit', 'Grass', 'Lion', 'Daisy'], answer: 2 },
    { id: 272, subject: 'Biology', grade: 4, question: 'What is the difference between a pond and an ocean habitat?', options: ['They are the same', 'A pond is freshwater and small; an ocean is saltwater and vast', 'Ponds are saltwater', 'Oceans are freshwater'], answer: 1 },
    { id: 273, subject: 'Biology', grade: 5, question: 'What is the difference between deciduous and evergreen trees?', options: ['They are the same', 'Deciduous trees lose their leaves seasonally; evergreens keep theirs year-round', 'Evergreens lose leaves', 'Deciduous trees are always green'], answer: 1 },
    { id: 274, subject: 'Biology', grade: 5, question: 'What is the function of the epiglottis?', options: ['To help digest food', 'To cover the windpipe during swallowing to prevent choking', 'To filter blood', 'To produce sound'], answer: 1 },
    { id: 275, subject: 'Biology', grade: 6, question: 'What is the difference between herbivore and carnivore in an ecosystem?', options: ['They are the same', 'Herbivores eat plants; carnivores eat animals', 'Carnivores eat plants', 'Herbivores eat animals'], answer: 1 },
    { id: 276, subject: 'Biology', grade: 6, question: 'What is decomposition?', options: ['Building something new', 'The breakdown of dead organic matter by decomposers', 'A type of growth', 'Photosynthesis'], answer: 1 },
    { id: 277, subject: 'Biology', grade: 7, question: 'What is peristalsis?', options: ['A disease', 'Wavelike muscle contractions that move food through the digestive tract', 'A type of cell division', 'A breathing technique'], answer: 1 },
    { id: 278, subject: 'Biology', grade: 7, question: 'What are the chambers of the human heart?', options: ['One chamber', 'Two atria and two ventricles', 'Three chambers', 'Five chambers'], answer: 1 },
    { id: 279, subject: 'Biology', grade: 8, question: 'What is the difference between sexual and asexual reproduction?', options: ['They are the same', 'Sexual requires two parents and produces genetic variation; asexual requires one parent and produces clones', 'Asexual requires two parents', 'Sexual produces clones'], answer: 1 },
    { id: 280, subject: 'Biology', grade: 8, question: 'What is binary fission?', options: ['A type of sexual reproduction', 'A form of asexual reproduction where a cell splits into two identical cells', 'Cell death', 'Meiosis'], answer: 1 },
    { id: 281, subject: 'Biology', grade: 9, question: 'What is eutrophication?', options: ['Clean water', 'Excessive nutrient enrichment in water leading to algal blooms and oxygen depletion', 'Water evaporation', 'Water purification'], answer: 1 },
    { id: 282, subject: 'Biology', grade: 9, question: 'What is the greenhouse effect in relation to ecology?', options: ['A gardening technique', 'The trapping of heat in the atmosphere by greenhouse gases, affecting ecosystems', 'A type of photosynthesis', 'Only occurs in greenhouses'], answer: 1 },
    { id: 283, subject: 'Biology', grade: 10, question: 'What is a signal transduction pathway?', options: ['A road', 'A series of molecular events by which a cell converts an external signal into a cellular response', 'A nerve pathway only', 'A blood vessel'], answer: 1 },
    { id: 284, subject: 'Biology', grade: 10, question: 'What is the difference between proto-oncogenes and oncogenes?', options: ['They are the same', 'Proto-oncogenes are normal genes regulating cell growth; oncogenes are mutated versions that can cause cancer', 'Oncogenes are normal', 'Proto-oncogenes cause cancer'], answer: 1 },
    { id: 285, subject: 'Biology', grade: 8, question: 'What is a pathogen?', options: ['A helpful bacterium', 'A microorganism that causes disease', 'A type of white blood cell', 'A nutrient'], answer: 1 }
  ],
  [
    { id: 286, subject: 'Biology', grade: 4, question: 'What do earthworms do for soil?', options: ['Make it drier', 'Help aerate and enrich the soil', 'Make it harder', 'Nothing'], answer: 1 },
    { id: 287, subject: 'Biology', grade: 4, question: 'Which animal can regrow its tail?', options: ['Dog', 'Cat', 'Lizard', 'Horse'], answer: 2 },
    { id: 288, subject: 'Biology', grade: 5, question: 'What is the trachea also known as?', options: ['Food pipe', 'Windpipe', 'Blood vessel', 'Nerve cord'], answer: 1 },
    { id: 289, subject: 'Biology', grade: 5, question: 'What are the two types of blood circulation in the body?', options: ['Fast and slow', 'Pulmonary (to lungs) and systemic (to body)', 'Upper and lower', 'Internal and external'], answer: 1 },
    { id: 290, subject: 'Biology', grade: 6, question: 'What is the importance of wetlands?', options: ['They have no importance', 'They filter water, prevent flooding, and provide habitat for many species', 'They are wastelands', 'They only grow grass'], answer: 1 },
    { id: 291, subject: 'Biology', grade: 6, question: 'What is a tundra biome?', options: ['A hot desert', 'A cold, treeless region with permafrost', 'A tropical forest', 'A grassland'], answer: 1 },
    { id: 292, subject: 'Biology', grade: 7, question: 'What is the function of the spleen?', options: ['Produces bile', 'Filters blood and recycles old red blood cells', 'Digests food', 'Produces insulin'], answer: 1 },
    { id: 293, subject: 'Biology', grade: 7, question: 'What is an organ system?', options: ['A single organ', 'A group of organs that work together to perform a major function', 'A single cell', 'A tissue'], answer: 1 },
    { id: 294, subject: 'Biology', grade: 8, question: 'What is the function of the lymphatic system?', options: ['To digest food', 'To help fight infections and return fluid to the bloodstream', 'To pump blood', 'To produce hormones'], answer: 1 },
    { id: 295, subject: 'Biology', grade: 8, question: 'What is an autoimmune disease?', options: ['A disease caused by bacteria', 'A condition where the immune system attacks the body\'s own cells', 'A type of cancer', 'An inherited eye color'], answer: 1 },
    { id: 296, subject: 'Biology', grade: 9, question: 'What is a phylogenetic tree?', options: ['A type of plant', 'A diagram showing evolutionary relationships among species', 'A food web', 'A cell diagram'], answer: 1 },
    { id: 297, subject: 'Biology', grade: 9, question: 'What is convergent evolution?', options: ['Species becoming more different', 'Unrelated species evolving similar traits due to similar environments', 'Species going extinct', 'Species not changing'], answer: 1 },
    { id: 298, subject: 'Biology', grade: 10, question: 'What is angiogenesis?', options: ['Cell death', 'The formation of new blood vessels, often important in tumor growth', 'Nerve growth', 'Bone formation'], answer: 1 },
    { id: 299, subject: 'Biology', grade: 10, question: 'What is the role of telomeres?', options: ['They code for proteins', 'They protect chromosome ends from deterioration during cell division', 'They produce energy', 'They store nutrients'], answer: 1 },
    { id: 300, subject: 'Biology', grade: 9, question: 'What is divergent evolution?', options: ['Species becoming more similar', 'Related species evolving different traits as they adapt to different environments', 'Extinction', 'No change over time'], answer: 1 }
  ],
  [
    { id: 301, subject: 'Biology', grade: 4, question: 'What season do many birds migrate south?', options: ['Summer', 'Winter', 'Spring', 'They never migrate'], answer: 1 },
    { id: 302, subject: 'Biology', grade: 4, question: 'What is a group of fish called?', options: ['Herd', 'School', 'Pack', 'Flock'], answer: 1 },
    { id: 303, subject: 'Biology', grade: 5, question: 'What is the role of blood vessels?', options: ['To store food', 'To carry blood throughout the body', 'To produce hormones', 'To filter waste'], answer: 1 },
    { id: 304, subject: 'Biology', grade: 5, question: 'What is an instinct?', options: ['A learned behavior', 'An inborn behavior that an animal is born knowing', 'A type of food', 'A habitat'], answer: 1 },
    { id: 305, subject: 'Biology', grade: 6, question: 'What is competition in an ecology context?', options: ['A game', 'When organisms struggle for the same limited resources', 'Cooperation', 'Mutualism'], answer: 1 },
    { id: 306, subject: 'Biology', grade: 6, question: 'What is the role of the sun in an ecosystem?', options: ['It has no role', 'It provides the initial energy source for almost all ecosystems', 'It only heats water', 'It only provides light for animals to see'], answer: 1 },
    { id: 307, subject: 'Biology', grade: 7, question: 'What is a reflex arc?', options: ['A type of exercise', 'The pathway of a nerve impulse during a reflex action from receptor to effector', 'A blood vessel', 'A digestive process'], answer: 1 },
    { id: 308, subject: 'Biology', grade: 7, question: 'What is the difference between arteries and veins?', options: ['They are the same', 'Arteries carry blood away from the heart; veins carry blood toward the heart', 'Veins carry blood away from the heart', 'Arteries are blue'], answer: 1 },
    { id: 309, subject: 'Biology', grade: 8, question: 'What are multiple alleles?', options: ['Only two alleles exist', 'Three or more alleles for a gene that exist in a population, such as blood type', 'One allele per gene', 'No alleles'], answer: 1 },
    { id: 310, subject: 'Biology', grade: 8, question: 'What blood types are possible in humans?', options: ['Only A and B', 'A, B, AB, and O', 'Only O', 'A and O only'], answer: 1 },
    { id: 311, subject: 'Biology', grade: 9, question: 'What is coevolution?', options: ['Evolution of one species', 'Two or more species evolving in response to each other over time', 'Extinction of both species', 'No evolution occurring'], answer: 1 },
    { id: 312, subject: 'Biology', grade: 9, question: 'What is the role of NADH in cellular respiration?', options: ['It is a waste product', 'It is an electron carrier that donates electrons to the electron transport chain', 'It is a sugar', 'It is an enzyme'], answer: 1 },
    { id: 313, subject: 'Biology', grade: 10, question: 'What is a stem cell niche?', options: ['A type of organ', 'The microenvironment that maintains stem cell properties and regulates their behavior', 'A laboratory tool', 'A type of tissue'], answer: 1 },
    { id: 314, subject: 'Biology', grade: 10, question: 'What is metagenomics?', options: ['Studying one gene', 'The study of genetic material recovered directly from environmental samples', 'A type of mutation', 'Cloning technique'], answer: 1 },
    { id: 315, subject: 'Biology', grade: 10, question: 'What is the microbiome?', options: ['A single bacterium', 'The community of microorganisms living in and on the human body or an environment', 'A type of cell', 'A microscope'], answer: 1 }
  ],
  [
    { id: 316, subject: 'Biology', grade: 4, question: 'What does a caterpillar turn into?', options: ['A worm', 'A butterfly or moth', 'A beetle', 'A spider'], answer: 1 },
    { id: 317, subject: 'Biology', grade: 4, question: 'What do bees collect from flowers?', options: ['Water', 'Nectar', 'Seeds', 'Leaves'], answer: 1 },
    { id: 318, subject: 'Biology', grade: 5, question: 'Which vitamin do you get from sunlight?', options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin E'], answer: 2 },
    { id: 319, subject: 'Biology', grade: 5, question: 'What is the function of the pancreas?', options: ['Pumps blood', 'Produces insulin and digestive enzymes', 'Filters air', 'Stores bile'], answer: 1 },
    { id: 320, subject: 'Biology', grade: 6, question: 'What is a rainforest biome characterized by?', options: ['Low rainfall and few trees', 'High rainfall, warm temperatures, and incredible biodiversity', 'Cold temperatures', 'No plants'], answer: 1 },
    { id: 321, subject: 'Biology', grade: 6, question: 'What is the energy pyramid?', options: ['A building in Egypt', 'A model showing energy decreases at each trophic level', 'A type of food chain', 'Energy increases at each level'], answer: 1 },
    { id: 322, subject: 'Biology', grade: 7, question: 'What is plasma in blood?', options: ['A type of cell', 'The liquid portion of blood that carries cells, nutrients, and waste', 'A gas', 'A solid'], answer: 1 },
    { id: 323, subject: 'Biology', grade: 7, question: 'What is the function of the cerebellum?', options: ['Controls emotions', 'Coordinates voluntary movement and balance', 'Regulates breathing', 'Processes vision'], answer: 1 },
    { id: 324, subject: 'Biology', grade: 8, question: 'What determines Rh factor in blood?', options: ['Diet', 'The presence or absence of a specific protein on red blood cells', 'Age', 'Gender only'], answer: 1 },
    { id: 325, subject: 'Biology', grade: 8, question: 'What is epistasis?', options: ['A gene acting alone', 'When one gene masks or modifies the expression of another gene', 'A type of mutation', 'A chromosome abnormality'], answer: 1 },
    { id: 326, subject: 'Biology', grade: 9, question: 'What is the difference between C3 and C4 photosynthesis?', options: ['They are the same', 'C4 plants have an additional step to concentrate CO2 and are more efficient in hot climates', 'C3 is more efficient in hot climates', 'C4 plants do not use CO2'], answer: 1 },
    { id: 327, subject: 'Biology', grade: 9, question: 'What is a monomer?', options: ['A large molecule', 'A small molecule that can bond with others to form a polymer', 'A type of cell', 'An organ'], answer: 1 },
    { id: 328, subject: 'Biology', grade: 10, question: 'What is bioethics?', options: ['A type of biology experiment', 'The study of ethical issues arising from advances in biology and medicine', 'A cell process', 'A type of organism'], answer: 1 },
    { id: 329, subject: 'Biology', grade: 10, question: 'What is a regulatory gene?', options: ['A gene that codes for a structural protein', 'A gene that controls the expression of other genes', 'A mutated gene', 'A gene found only in bacteria'], answer: 1 },
    { id: 330, subject: 'Biology', grade: 4, question: 'Which part of the body do you use to smell?', options: ['Eyes', 'Ears', 'Nose', 'Hands'], answer: 2 }
  ],
  [
    { id: 331, subject: 'Biology', grade: 4, question: 'What animal is known for building dams?', options: ['Bear', 'Beaver', 'Rabbit', 'Deer'], answer: 1 },
    { id: 332, subject: 'Biology', grade: 4, question: 'What is a group of wolves called?', options: ['Herd', 'Flock', 'Pack', 'School'], answer: 2 },
    { id: 333, subject: 'Biology', grade: 5, question: 'What carries oxygen in the blood?', options: ['White blood cells', 'Hemoglobin in red blood cells', 'Platelets', 'Plasma only'], answer: 1 },
    { id: 334, subject: 'Biology', grade: 5, question: 'What is the difference between a food chain and a food web?', options: ['They are the same', 'A food chain is a single path of energy; a food web shows multiple interconnected paths', 'A food web is simpler', 'A food chain is more complex'], answer: 1 },
    { id: 335, subject: 'Biology', grade: 6, question: 'What is biological magnification?', options: ['Making things look bigger', 'The process by which toxins become more concentrated at higher trophic levels', 'A type of magnifying glass', 'Cell growth'], answer: 1 },
    { id: 336, subject: 'Biology', grade: 6, question: 'What is the ozone layer important for?', options: ['Keeping the Earth warm only', 'Protecting living things from harmful ultraviolet radiation', 'Producing oxygen', 'Creating rain'], answer: 1 },
    { id: 337, subject: 'Biology', grade: 7, question: 'What is the function of the medulla oblongata?', options: ['Controls voluntary movement', 'Controls involuntary functions like breathing and heart rate', 'Processes memories', 'Controls speech'], answer: 1 },
    { id: 338, subject: 'Biology', grade: 7, question: 'What are neurons?', options: ['Muscle cells', 'Nerve cells that transmit electrical signals', 'Blood cells', 'Bone cells'], answer: 1 },
    { id: 339, subject: 'Biology', grade: 8, question: 'What is polygenic inheritance?', options: ['One gene controls one trait', 'A trait controlled by two or more genes, such as skin color or height', 'A trait with only two alleles', 'Traits controlled by the environment only'], answer: 1 },
    { id: 340, subject: 'Biology', grade: 8, question: 'What is a test cross?', options: ['A school exam', 'Crossing an organism with an unknown genotype with a homozygous recessive organism to determine the unknown genotype', 'A blood test', 'A DNA test only'], answer: 1 },
    { id: 341, subject: 'Biology', grade: 9, question: 'What is a polymer?', options: ['A single small molecule', 'A large molecule made up of repeating monomers', 'A type of element', 'An atom'], answer: 1 },
    { id: 342, subject: 'Biology', grade: 9, question: 'What is dehydration synthesis?', options: ['Removing water from the body', 'A chemical reaction that joins monomers by removing a water molecule', 'Drinking water', 'Breaking down polymers'], answer: 1 },
    { id: 343, subject: 'Biology', grade: 10, question: 'What is an operon?', options: ['A type of organ', 'A cluster of genes in prokaryotes transcribed together under the control of a single promoter', 'A eukaryotic structure', 'A type of protein'], answer: 1 },
    { id: 344, subject: 'Biology', grade: 10, question: 'What is the lac operon?', options: ['An operon that is always active', 'An operon in E. coli activated in the presence of lactose to produce enzymes for lactose metabolism', 'An operon for DNA repair', 'An operon for photosynthesis'], answer: 1 },
    { id: 345, subject: 'Biology', grade: 5, question: 'What is the function of the spinal cord?', options: ['To digest food', 'To carry messages between the brain and the rest of the body', 'To pump blood', 'To filter air'], answer: 1 }
  ],
  [
    { id: 346, subject: 'Biology', grade: 4, question: 'Which of these is prey?', options: ['Wolf', 'Eagle', 'Rabbit', 'Shark'], answer: 2 },
    { id: 347, subject: 'Biology', grade: 4, question: 'What do plants absorb through their leaves?', options: ['Soil', 'Carbon dioxide and sunlight', 'Rocks', 'Fish'], answer: 1 },
    { id: 348, subject: 'Biology', grade: 5, question: 'What is the role of the tongue in digestion?', options: ['It only tastes food', 'It helps move food around the mouth and push it toward the throat', 'It digests protein', 'It absorbs nutrients'], answer: 1 },
    { id: 349, subject: 'Biology', grade: 5, question: 'What is the difference between voluntary and involuntary muscles?', options: ['They are the same', 'Voluntary muscles you can control; involuntary muscles work automatically', 'Involuntary muscles you control', 'All muscles are voluntary'], answer: 1 },
    { id: 350, subject: 'Biology', grade: 6, question: 'What is deforestation?', options: ['Planting trees', 'The clearing of forests by cutting or burning trees', 'Growing a garden', 'Building a dam'], answer: 1 },
    { id: 351, subject: 'Biology', grade: 6, question: 'What is biodiversity?', options: ['Having only one species', 'The variety of different species of life in an area', 'A type of biome', 'A single ecosystem'], answer: 1 },
    { id: 352, subject: 'Biology', grade: 7, question: 'What is a synapse?', options: ['A type of bone', 'The gap between two neurons where signals are transmitted', 'A blood vessel', 'A muscle fiber'], answer: 1 },
    { id: 353, subject: 'Biology', grade: 7, question: 'What is the function of the cerebrum?', options: ['Controls balance only', 'The largest part of the brain responsible for thought, memory, and voluntary actions', 'Controls breathing only', 'Produces hormones only'], answer: 1 },
    { id: 354, subject: 'Biology', grade: 8, question: 'What is the difference between genotype and phenotype?', options: ['They are the same', 'Genotype is the genetic makeup; phenotype is the observable traits', 'Phenotype is the genes', 'Genotype is what you see'], answer: 1 },
    { id: 355, subject: 'Biology', grade: 8, question: 'What is a chromosome?', options: ['A type of protein', 'A thread-like structure of DNA and protein found in the nucleus that carries genes', 'A cell membrane', 'An organelle'], answer: 1 },
    { id: 356, subject: 'Biology', grade: 9, question: 'What is hydrolysis?', options: ['Building polymers', 'Breaking down polymers by adding water molecules', 'Removing water', 'Dehydration'], answer: 1 },
    { id: 357, subject: 'Biology', grade: 9, question: 'What is adaptive radiation?', options: ['A type of nuclear energy', 'The diversification of a species into several different forms that are each adapted to different environments', 'A single mutation', 'Cell death'], answer: 1 },
    { id: 358, subject: 'Biology', grade: 10, question: 'What is a homologous structure?', options: ['Structures with different origins', 'Structures in different species that share a common evolutionary origin but may have different functions', 'Identical structures', 'Structures with no relation'], answer: 1 },
    { id: 359, subject: 'Biology', grade: 10, question: 'What is an analogous structure?', options: ['Structures with a common ancestor', 'Structures in different species with similar functions but different evolutionary origins', 'Identical structures', 'Vestigial structures'], answer: 1 },
    { id: 360, subject: 'Biology', grade: 6, question: 'What is the greenhouse effect?', options: ['A gardening technique', 'The trapping of the sun\'s heat in Earth\'s atmosphere by certain gases', 'A type of plant growth', 'Only occurs in greenhouses'], answer: 1 }
  ],
  [
    { id: 361, subject: 'Biology', grade: 4, question: 'What happens to water inside a plant?', options: ['It stays in the roots', 'It moves up through the stem to the leaves', 'It turns into soil', 'It becomes seeds'], answer: 1 },
    { id: 362, subject: 'Biology', grade: 4, question: 'Which living thing can make its own food?', options: ['Cat', 'Dog', 'Sunflower', 'Worm'], answer: 2 },
    { id: 363, subject: 'Biology', grade: 5, question: 'What are joints?', options: ['Types of bones', 'Places where two or more bones meet, allowing movement', 'Types of muscles', 'Parts of the skin'], answer: 1 },
    { id: 364, subject: 'Biology', grade: 5, question: 'What is the role of the diaphragm in breathing?', options: ['It pumps blood', 'It contracts and relaxes to help draw air into and push air out of the lungs', 'It filters air', 'It produces mucus'], answer: 1 },
    { id: 365, subject: 'Biology', grade: 6, question: 'What is an endangered species?', options: ['A very common species', 'A species whose population is so small it is at risk of extinction', 'An extinct species', 'A newly discovered species'], answer: 1 },
    { id: 366, subject: 'Biology', grade: 6, question: 'What is conservation?', options: ['Using all resources quickly', 'The protection and preservation of natural resources and wildlife', 'Cutting down forests', 'Polluting water'], answer: 1 },
    { id: 367, subject: 'Biology', grade: 7, question: 'What is the difference between sensory and motor neurons?', options: ['They are the same', 'Sensory neurons carry signals to the brain; motor neurons carry signals from the brain to muscles', 'Motor neurons sense the environment', 'Sensory neurons control muscles'], answer: 1 },
    { id: 368, subject: 'Biology', grade: 7, question: 'What is the role of the hypothalamus?', options: ['Controls voluntary movement', 'Regulates body temperature, hunger, thirst, and links the nervous and endocrine systems', 'Produces bile', 'Filters blood'], answer: 1 },
    { id: 369, subject: 'Biology', grade: 8, question: 'What is crossing over important for?', options: ['Identical offspring', 'Increasing genetic diversity by shuffling genes between homologous chromosomes', 'Reducing chromosome number', 'Cell growth'], answer: 1 },
    { id: 370, subject: 'Biology', grade: 8, question: 'What is nondisjunction?', options: ['Normal cell division', 'The failure of chromosomes to separate properly during cell division, leading to abnormal chromosome numbers', 'A type of mutation', 'DNA replication'], answer: 1 },
    { id: 371, subject: 'Biology', grade: 9, question: 'What is stabilizing selection?', options: ['Selection that favors extreme traits', 'Natural selection that favors intermediate phenotypes, reducing variation', 'Selection that favors one extreme', 'Random selection'], answer: 1 },
    { id: 372, subject: 'Biology', grade: 9, question: 'What is directional selection?', options: ['Selection favoring average traits', 'Natural selection that favors one extreme phenotype over others', 'Selection against all traits', 'No selection occurring'], answer: 1 },
    { id: 373, subject: 'Biology', grade: 10, question: 'What is a vestigial structure in humans?', options: ['The heart', 'The appendix, which has lost most of its original function', 'The brain', 'The liver'], answer: 1 },
    { id: 374, subject: 'Biology', grade: 10, question: 'What is comparative genomics?', options: ['Studying one genome', 'Comparing genomes of different species to understand evolutionary relationships and gene function', 'A type of mutation', 'A cell division technique'], answer: 1 },
    { id: 375, subject: 'Biology', grade: 7, question: 'What is the bronchi?', options: ['Part of the stomach', 'The two main airways that branch from the trachea into the lungs', 'A type of muscle', 'A blood vessel'], answer: 1 }
  ],
  [
    { id: 376, subject: 'Biology', grade: 4, question: 'What is a food source for a frog?', options: ['Grass', 'Insects', 'Seeds', 'Leaves'], answer: 1 },
    { id: 377, subject: 'Biology', grade: 4, question: 'Where do polar bears live?', options: ['Desert', 'Arctic', 'Rainforest', 'Ocean floor'], answer: 1 },
    { id: 378, subject: 'Biology', grade: 5, question: 'What happens when you exercise?', options: ['Your heart rate decreases', 'Your heart rate increases and you breathe faster to supply more oxygen', 'Nothing changes', 'Your bones grow faster'], answer: 1 },
    { id: 379, subject: 'Biology', grade: 5, question: 'What is the function of sweat?', options: ['To make you smell', 'To cool the body down when it is overheating', 'To digest food', 'To carry oxygen'], answer: 1 },
    { id: 380, subject: 'Biology', grade: 6, question: 'How do plants reproduce using spores?', options: ['They use seeds only', 'Ferns and mosses release tiny spores that grow into new plants', 'They use fruits', 'They cannot reproduce'], answer: 1 },
    { id: 381, subject: 'Biology', grade: 6, question: 'What is a savanna biome?', options: ['A frozen tundra', 'A tropical grassland with scattered trees and distinct wet and dry seasons', 'A dense forest', 'An ocean environment'], answer: 1 },
    { id: 382, subject: 'Biology', grade: 7, question: 'What is the function of cartilage?', options: ['To produce blood', 'To provide flexible support and cushioning between bones', 'To transmit nerve signals', 'To digest food'], answer: 1 },
    { id: 383, subject: 'Biology', grade: 7, question: 'What is the function of ligaments?', options: ['Connect muscles to bones', 'Connect bones to bones at joints', 'Carry blood', 'Produce hormones'], answer: 1 },
    { id: 384, subject: 'Biology', grade: 8, question: 'What are autosomes?', options: ['Sex chromosomes', 'Chromosomes that are not sex chromosomes (humans have 22 pairs)', 'Genes', 'Alleles'], answer: 1 },
    { id: 385, subject: 'Biology', grade: 8, question: 'What is genetic counseling?', options: ['Therapy for stress', 'A process where professionals help individuals understand genetic risks and make informed decisions', 'A type of surgery', 'A school course'], answer: 1 },
    { id: 386, subject: 'Biology', grade: 9, question: 'What is disruptive selection?', options: ['Selection favoring the average', 'Natural selection that favors both extreme phenotypes over intermediate ones', 'Selection favoring one extreme', 'Artificial selection'], answer: 1 },
    { id: 387, subject: 'Biology', grade: 9, question: 'What is the bottleneck effect?', options: ['A population growing rapidly', 'A sharp reduction in population size due to an event, reducing genetic diversity', 'A type of mutation', 'Gene flow'], answer: 1 },
    { id: 388, subject: 'Biology', grade: 10, question: 'What is bioinformatics?', options: ['A type of biology class', 'The use of computer science and statistics to analyze and interpret biological data', 'A cell process', 'A type of organism'], answer: 1 },
    { id: 389, subject: 'Biology', grade: 10, question: 'What is a knockout organism?', options: ['An organism that fights', 'An organism in which a specific gene has been inactivated to study its function', 'A dead organism', 'A cloned organism'], answer: 1 },
    { id: 390, subject: 'Biology', grade: 8, question: 'What is the Human Genome Project?', options: ['A building project', 'An international research effort to map all human genes', 'A type of vaccine', 'A genetic disease'], answer: 1 }
  ],
  [
    { id: 391, subject: 'Biology', grade: 4, question: 'What do we call a scientist who studies living things?', options: ['Chemist', 'Biologist', 'Physicist', 'Geologist'], answer: 1 },
    { id: 392, subject: 'Biology', grade: 4, question: 'What is the difference between a frog and a toad?', options: ['They are exactly the same', 'Frogs have smooth moist skin; toads have dry bumpy skin', 'Toads live in water only', 'Frogs have scales'], answer: 1 },
    { id: 393, subject: 'Biology', grade: 5, question: 'What is a vertebrate?', options: ['An animal without a backbone', 'An animal with a backbone', 'A type of plant', 'A type of fungus'], answer: 1 },
    { id: 394, subject: 'Biology', grade: 5, question: 'What is an invertebrate?', options: ['An animal with a backbone', 'An animal without a backbone', 'A type of tree', 'A mineral'], answer: 1 },
    { id: 395, subject: 'Biology', grade: 7, question: 'What is an enzyme in digestion?', options: ['A type of food', 'A protein that speeds up the breakdown of food molecules', 'A bone', 'A blood cell'], answer: 1 },
    { id: 396, subject: 'Biology', grade: 7, question: 'What is bile and where is it produced?', options: ['A hormone made in the pancreas', 'A digestive fluid produced by the liver that helps break down fats', 'A type of blood cell', 'An enzyme from the stomach'], answer: 1 },
    { id: 397, subject: 'Biology', grade: 8, question: 'What are GMOs?', options: ['Natural organisms', 'Genetically modified organisms whose DNA has been altered using genetic engineering', 'A type of fertilizer', 'Organic foods'], answer: 1 },
    { id: 398, subject: 'Biology', grade: 8, question: 'What is cloning?', options: ['Sexual reproduction', 'Creating a genetically identical copy of an organism', 'Mutation', 'Natural selection'], answer: 1 },
    { id: 399, subject: 'Biology', grade: 9, question: 'What is the founder effect?', options: ['A large population splitting', 'Loss of genetic variation when a small group establishes a new population', 'A type of natural selection', 'Gene mutation'], answer: 1 },
    { id: 400, subject: 'Biology', grade: 9, question: 'What is a vestigial structure?', options: ['A new adaptation', 'A structure that has lost most or all of its original function through evolution', 'A fully functional organ', 'A mutation'], answer: 1 },
    { id: 401, subject: 'Biology', grade: 10, question: 'What is the difference between totipotent and pluripotent stem cells?', options: ['They are the same', 'Totipotent cells can become any cell type including placenta; pluripotent can become almost any type but not placenta', 'Pluripotent is more versatile', 'Neither can differentiate'], answer: 1 },
    { id: 402, subject: 'Biology', grade: 10, question: 'What is the role of primase in DNA replication?', options: ['It unwinds DNA', 'It synthesizes a short RNA primer to initiate DNA synthesis', 'It joins Okazaki fragments', 'It proofreads the new strand'], answer: 1 },
    { id: 403, subject: 'Biology', grade: 9, question: 'What is biogeography?', options: ['The study of cells', 'The study of the geographic distribution of species and how it relates to evolution', 'A type of biome', 'Genetics'], answer: 1 }
  ],
  [
    { id: 404, subject: 'Biology', grade: 4, question: 'Which body part do you use to taste food?', options: ['Nose', 'Fingers', 'Tongue', 'Ears'], answer: 2 },
    { id: 405, subject: 'Biology', grade: 4, question: 'What is a cocoon?', options: ['A type of food', 'A protective covering a caterpillar makes during metamorphosis', 'A bird nest', 'A type of seed'], answer: 1 },
    { id: 406, subject: 'Biology', grade: 5, question: 'How does a chameleon protect itself?', options: ['By running fast', 'By changing color to blend with its surroundings', 'By spraying venom', 'By flying away'], answer: 1 },
    { id: 407, subject: 'Biology', grade: 8, question: 'What is gene therapy?', options: ['Physical therapy', 'A technique that uses genes to treat or prevent disease by correcting defective genes', 'A type of surgery', 'A type of vaccine'], answer: 1 },
    { id: 408, subject: 'Biology', grade: 9, question: 'What are homologous structures?', options: ['Structures with different origins but same function', 'Structures in different species that share a common evolutionary origin', 'Identical structures', 'Structures with no relation'], answer: 1 },
    { id: 409, subject: 'Biology', grade: 10, question: 'What is the role of ligase in DNA replication?', options: ['It unwinds DNA', 'It joins Okazaki fragments together on the lagging strand', 'It adds nucleotides', 'It removes primers'], answer: 1 },
    { id: 410, subject: 'Biology', grade: 10, question: 'What is a missense mutation?', options: ['A silent mutation', 'A point mutation that results in a different amino acid being incorporated into the protein', 'A mutation that adds a stop codon', 'A deletion mutation'], answer: 1 },
    { id: 411, subject: 'Biology', grade: 10, question: 'What is a nonsense mutation?', options: ['A harmless mutation', 'A point mutation that creates a premature stop codon, producing a shortened protein', 'A mutation that changes nothing', 'An insertion mutation'], answer: 1 }
  ],
  [
    { id: 412, subject: 'Biology', grade: 4, question: 'What is the main purpose of fur on animals?', options: ['Decoration', 'To keep them warm', 'To help them swim', 'To attract mates only'], answer: 1 }
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ],
  [
  ]
];

module.exports = { biologyTestBanks };
