const englishTestBanks = [
  // TEST 1
  [
    { id: 1, subject: 'English', grade: 4, question: 'Which word is a noun in the sentence: "The cat sat on the mat"?', options: ['sat', 'on', 'the', 'cat'], answer: 3 },
    { id: 2, subject: 'English', grade: 4, question: 'What is the plural of "child"?', options: ['childs', 'childrens', 'children', 'childes'], answer: 2 },
    { id: 3, subject: 'English', grade: 5, question: 'Which sentence uses correct punctuation?', options: ['I like dogs cats and birds.', 'I like dogs, cats, and birds.', 'I like dogs cats, and birds.', 'I like, dogs cats and birds.'], answer: 1 },
    { id: 4, subject: 'English', grade: 5, question: 'What is a synonym for "happy"?', options: ['sad', 'joyful', 'angry', 'tired'], answer: 1 },
    { id: 5, subject: 'English', grade: 6, question: 'What type of sentence is "Close the door"?', options: ['declarative', 'interrogative', 'imperative', 'exclamatory'], answer: 2 },
    { id: 6, subject: 'English', grade: 6, question: 'Which word is an adverb in "She quickly ran home"?', options: ['She', 'quickly', 'ran', 'home'], answer: 1 },
    { id: 7, subject: 'English', grade: 7, question: 'What is a simile?', options: ['A comparison using "like" or "as"', 'A direct comparison without "like" or "as"', 'An exaggeration', 'Giving human traits to non-human things'], answer: 0 },
    { id: 8, subject: 'English', grade: 7, question: 'Which sentence is in the passive voice?', options: ['The dog chased the cat.', 'She wrote a letter.', 'The cake was eaten by the children.', 'He runs every morning.'], answer: 2 },
    { id: 9, subject: 'English', grade: 8, question: 'What does the prefix "un-" mean?', options: ['again', 'not', 'before', 'after'], answer: 1 },
    { id: 10, subject: 'English', grade: 8, question: 'Which sentence demonstrates parallel structure?', options: ['She likes swimming, to run, and biking.', 'She likes swimming, running, and biking.', 'She likes to swim, running, and to bike.', 'She likes swim, to run, and biking.'], answer: 1 },
    { id: 11, subject: 'English', grade: 9, question: 'What literary device is used in "The wind whispered through the trees"?', options: ['simile', 'personification', 'hyperbole', 'alliteration'], answer: 1 },
    { id: 12, subject: 'English', grade: 9, question: 'Which of these is an example of a thesis statement?', options: ['Dogs are animals.', 'This essay is about dogs.', 'Dogs make better pets than cats because of their loyalty, trainability, and companionship.', 'I like dogs.'], answer: 2 },
    { id: 13, subject: 'English', grade: 10, question: 'What is an ad hominem fallacy?', options: ['Attacking the person instead of the argument', 'Appealing to emotion', 'Using a false analogy', 'Making a hasty generalization'], answer: 0 },
    { id: 14, subject: 'English', grade: 10, question: 'In literary analysis, what does "tone" refer to?', options: ['The sequence of events', 'The author\'s attitude toward the subject', 'The main character\'s personality', 'The setting of the story'], answer: 1 },
    { id: 15, subject: 'English', grade: 4, question: 'Which word is a verb in "The bird sings a beautiful song"?', options: ['bird', 'sings', 'beautiful', 'song'], answer: 1 }
  ],
  // TEST 2
  [
    { id: 16, subject: 'English', grade: 4, question: 'What is the opposite of "big"?', options: ['large', 'huge', 'small', 'tall'], answer: 2 },
    { id: 17, subject: 'English', grade: 4, question: 'Which word is an adjective in "The red ball bounced high"?', options: ['The', 'red', 'bounced', 'high'], answer: 1 },
    { id: 18, subject: 'English', grade: 5, question: 'What does the suffix "-ful" mean in "careful"?', options: ['without', 'full of', 'able to', 'one who'], answer: 1 },
    { id: 19, subject: 'English', grade: 5, question: 'Which sentence has a compound subject?', options: ['The dog ran fast.', 'Tom and Jerry played outside.', 'She ate lunch quickly.', 'The car is red.'], answer: 1 },
    { id: 20, subject: 'English', grade: 6, question: 'What is an antonym for "ancient"?', options: ['old', 'modern', 'historic', 'aged'], answer: 1 },
    { id: 21, subject: 'English', grade: 6, question: 'Which word is a conjunction in "I wanted to go, but it was raining"?', options: ['wanted', 'go', 'but', 'raining'], answer: 2 },
    { id: 22, subject: 'English', grade: 7, question: 'What is a metaphor?', options: ['A comparison using "like"', 'A direct comparison without "like" or "as"', 'An exaggeration for effect', 'A reference to another work'], answer: 1 },
    { id: 23, subject: 'English', grade: 7, question: 'Which sentence contains an appositive?', options: ['The dog barked loudly.', 'My brother, a talented musician, plays guitar.', 'She went to the store and bought milk.', 'Running is good exercise.'], answer: 1 },
    { id: 24, subject: 'English', grade: 8, question: 'What does the root word "bene" mean?', options: ['bad', 'good', 'life', 'write'], answer: 1 },
    { id: 25, subject: 'English', grade: 8, question: 'Which sentence uses a semicolon correctly?', options: ['I like pizza; and burgers.', 'I like pizza; it is my favorite food.', 'I like; pizza and burgers.', 'I; like pizza and burgers.'], answer: 1 },
    { id: 26, subject: 'English', grade: 9, question: 'What is alliteration?', options: ['Repetition of vowel sounds', 'Repetition of consonant sounds at the beginning of words', 'A comparison using "like"', 'An extreme exaggeration'], answer: 1 },
    { id: 27, subject: 'English', grade: 9, question: 'What is the purpose of a rhetorical question?', options: ['To get an answer from the audience', 'To make a point or create emphasis without expecting an answer', 'To confuse the reader', 'To end a paragraph'], answer: 1 },
    { id: 28, subject: 'English', grade: 10, question: 'What is a straw man fallacy?', options: ['Attacking someone personally', 'Misrepresenting someone\'s argument to make it easier to attack', 'Appealing to tradition', 'Using circular reasoning'], answer: 1 },
    { id: 29, subject: 'English', grade: 10, question: 'Which critical lens focuses on power structures and class struggle?', options: ['Feminist criticism', 'Marxist criticism', 'Psychoanalytic criticism', 'Formalist criticism'], answer: 1 },
    { id: 30, subject: 'English', grade: 5, question: 'What type of noun is "happiness"?', options: ['concrete noun', 'proper noun', 'abstract noun', 'collective noun'], answer: 2 }
  ],
  // TEST 3
  [
    { id: 31, subject: 'English', grade: 4, question: 'Which sentence is a question?', options: ['The sky is blue.', 'What a beautiful day!', 'Is the sky blue?', 'Look at the sky.'], answer: 2 },
    { id: 32, subject: 'English', grade: 4, question: 'What is the past tense of "run"?', options: ['runned', 'running', 'ran', 'runs'], answer: 2 },
    { id: 33, subject: 'English', grade: 5, question: 'Which word is a preposition in "The book is on the table"?', options: ['book', 'is', 'on', 'table'], answer: 2 },
    { id: 34, subject: 'English', grade: 5, question: 'What is a compound word?', options: ['A word with a prefix', 'A word made from two smaller words', 'A word with a suffix', 'A word with more than three syllables'], answer: 1 },
    { id: 35, subject: 'English', grade: 6, question: 'Which sentence uses "their" correctly?', options: ['Their going to the store.', 'They put their books away.', 'Their is a dog outside.', 'I went over their.'], answer: 1 },
    { id: 36, subject: 'English', grade: 6, question: 'What is the subject in "The tall man in the blue coat walked slowly"?', options: ['coat', 'walked', 'man', 'slowly'], answer: 2 },
    { id: 37, subject: 'English', grade: 7, question: 'What is hyperbole?', options: ['A comparison using "as"', 'A direct comparison', 'An extreme exaggeration not meant literally', 'Giving human traits to animals'], answer: 2 },
    { id: 38, subject: 'English', grade: 7, question: 'Which sentence is a complex sentence?', options: ['I went to the store.', 'I went to the store, and I bought milk.', 'Although it was raining, I went for a walk.', 'I went to the store, bought milk, and came home.'], answer: 2 },
    { id: 39, subject: 'English', grade: 8, question: 'What does the prefix "pre-" mean?', options: ['after', 'before', 'not', 'again'], answer: 1 },
    { id: 40, subject: 'English', grade: 8, question: 'What is the function of a topic sentence?', options: ['To conclude a paragraph', 'To provide evidence', 'To introduce the main idea of a paragraph', 'To transition between paragraphs'], answer: 2 },
    { id: 41, subject: 'English', grade: 9, question: 'What literary device is "The classroom was a zoo"?', options: ['simile', 'metaphor', 'hyperbole', 'onomatopoeia'], answer: 1 },
    { id: 42, subject: 'English', grade: 9, question: 'What is the difference between denotation and connotation?', options: ['Denotation is the emotional meaning; connotation is the literal meaning', 'Denotation is the dictionary meaning; connotation is the emotional or cultural meaning', 'They mean the same thing', 'Denotation is used in poetry; connotation is used in prose'], answer: 1 },
    { id: 43, subject: 'English', grade: 10, question: 'What is ethos in rhetoric?', options: ['An appeal to emotion', 'An appeal to logic', 'An appeal to credibility or character', 'An appeal to time'], answer: 2 },
    { id: 44, subject: 'English', grade: 10, question: 'Which critical lens examines literature through the lens of gender roles and inequality?', options: ['Marxist criticism', 'Formalist criticism', 'Feminist criticism', 'Historicist criticism'], answer: 2 },
    { id: 45, subject: 'English', grade: 6, question: 'What is the direct object in "She threw the ball"?', options: ['She', 'threw', 'the', 'ball'], answer: 3 }
  ],
  // TEST 4
  [
    { id: 46, subject: 'English', grade: 4, question: 'Which word correctly completes the sentence: "She ___ to school every day"?', options: ['walk', 'walks', 'walking', 'walked'], answer: 1 },
    { id: 47, subject: 'English', grade: 4, question: 'What is a pronoun?', options: ['A word that describes a noun', 'A word that takes the place of a noun', 'A word that shows action', 'A word that connects sentences'], answer: 1 },
    { id: 48, subject: 'English', grade: 5, question: 'Which sentence uses an apostrophe correctly?', options: ['The dogs bone is buried.', 'The dog\'s bone is buried.', 'The dogs\' bone is buried.', 'The dog\'s\' bone is buried.'], answer: 1 },
    { id: 49, subject: 'English', grade: 5, question: 'What does the suffix "-less" mean?', options: ['full of', 'without', 'able to', 'in the manner of'], answer: 1 },
    { id: 50, subject: 'English', grade: 6, question: 'Which word is an interjection?', options: ['quickly', 'Wow!', 'under', 'because'], answer: 1 },
    { id: 51, subject: 'English', grade: 6, question: 'What is the predicate in "The small kitten purred softly"?', options: ['The small kitten', 'kitten', 'purred softly', 'softly'], answer: 2 },
    { id: 52, subject: 'English', grade: 7, question: 'What is onomatopoeia?', options: ['A word that imitates a sound', 'A comparison using "like"', 'An exaggeration', 'A repeated consonant sound'], answer: 0 },
    { id: 53, subject: 'English', grade: 7, question: 'Which sentence uses a colon correctly?', options: ['I need: eggs, milk, and bread.', 'I need the following items: eggs, milk, and bread.', 'I: need eggs, milk, and bread.', 'I need the following: items eggs milk bread.'], answer: 1 },
    { id: 54, subject: 'English', grade: 8, question: 'What does the root "aud" mean?', options: ['see', 'hear', 'write', 'speak'], answer: 1 },
    { id: 55, subject: 'English', grade: 8, question: 'Which sentence correctly uses a conjunctive adverb?', options: ['I was tired, however I kept working.', 'I was tired; however, I kept working.', 'I was tired however, I kept working.', 'I was tired however; I kept working.'], answer: 1 },
    { id: 56, subject: 'English', grade: 9, question: 'What is irony?', options: ['A direct comparison', 'When the opposite of what is expected occurs', 'An exaggeration for humor', 'A reference to mythology'], answer: 1 },
    { id: 57, subject: 'English', grade: 9, question: 'What is the purpose of a counterargument in an essay?', options: ['To weaken your own argument', 'To confuse the reader', 'To acknowledge and refute opposing viewpoints', 'To introduce a new topic'], answer: 2 },
    { id: 58, subject: 'English', grade: 10, question: 'What is pathos in rhetoric?', options: ['An appeal to credibility', 'An appeal to logic', 'An appeal to emotion', 'An appeal to authority'], answer: 2 },
    { id: 59, subject: 'English', grade: 10, question: 'What is a red herring fallacy?', options: ['Attacking the person instead of the argument', 'Introducing an irrelevant topic to divert attention', 'Assuming the conclusion in the premise', 'Appealing to popular opinion'], answer: 1 },
    { id: 60, subject: 'English', grade: 7, question: 'What is the difference between "affect" and "effect"?', options: ['"Affect" is a noun; "effect" is a verb', '"Affect" is usually a verb; "effect" is usually a noun', 'They mean the same thing', '"Affect" is formal; "effect" is informal'], answer: 1 }
  ],
  // TEST 5
  [
    { id: 61, subject: 'English', grade: 4, question: 'Which word is a proper noun?', options: ['city', 'dog', 'Paris', 'river'], answer: 2 },
    { id: 62, subject: 'English', grade: 4, question: 'What punctuation mark ends a declarative sentence?', options: ['question mark', 'exclamation point', 'period', 'comma'], answer: 2 },
    { id: 63, subject: 'English', grade: 5, question: 'What is a homophone?', options: ['A word that means the same as another', 'A word that sounds the same as another but has a different meaning', 'A word that is spelled the same as another', 'A word with multiple syllables'], answer: 1 },
    { id: 64, subject: 'English', grade: 5, question: 'Which sentence uses quotation marks correctly?', options: ['She said "I am happy."', 'She said, "I am happy."', '"She said I am happy."', 'She "said, I am happy."'], answer: 1 },
    { id: 65, subject: 'English', grade: 6, question: 'What is a collective noun?', options: ['A noun that names a group', 'A noun that names a specific person', 'A noun that names an idea', 'A noun that names a place'], answer: 0 },
    { id: 66, subject: 'English', grade: 6, question: 'Which sentence uses "its" correctly?', options: ['Its a beautiful day.', 'The dog wagged its tail.', 'Its going to rain.', 'The cat licked it\'s paw.'], answer: 1 },
    { id: 67, subject: 'English', grade: 7, question: 'What is an oxymoron?', options: ['A combination of contradictory terms', 'A comparison using "like"', 'A play on words', 'An extreme exaggeration'], answer: 0 },
    { id: 68, subject: 'English', grade: 7, question: 'Which sentence demonstrates correct subject-verb agreement?', options: ['The group of students are ready.', 'The group of students is ready.', 'The group of students were ready.', 'The group of students have been ready.'], answer: 1 },
    { id: 69, subject: 'English', grade: 8, question: 'What does the suffix "-ology" mean?', options: ['fear of', 'study of', 'full of', 'state of'], answer: 1 },
    { id: 70, subject: 'English', grade: 8, question: 'What is a dangling modifier?', options: ['A modifier placed next to the word it modifies', 'A modifier that has no clear word to modify in the sentence', 'A type of adjective', 'A word that ends a sentence'], answer: 1 },
    { id: 71, subject: 'English', grade: 9, question: 'What is an allusion?', options: ['An illusion or trick', 'A reference to a well-known person, place, event, or work', 'A type of metaphor', 'A repeated phrase'], answer: 1 },
    { id: 72, subject: 'English', grade: 9, question: 'What is the difference between first-person and third-person point of view?', options: ['First person uses "he/she"; third person uses "I"', 'First person uses "I"; third person uses "he/she/they"', 'There is no difference', 'First person is past tense; third person is present tense'], answer: 1 },
    { id: 73, subject: 'English', grade: 10, question: 'What is logos in rhetoric?', options: ['An appeal to emotion', 'An appeal to credibility', 'An appeal to logic and reason', 'An appeal to tradition'], answer: 2 },
    { id: 74, subject: 'English', grade: 10, question: 'What is a slippery slope fallacy?', options: ['Arguing that one event will inevitably lead to a chain of negative events without evidence', 'Attacking someone personally', 'Using circular reasoning', 'Appealing to authority'], answer: 0 },
    { id: 75, subject: 'English', grade: 8, question: 'What is the difference between active and passive voice?', options: ['Active voice is past tense; passive voice is present tense', 'In active voice the subject performs the action; in passive voice the subject receives the action', 'They are the same thing', 'Active voice uses adjectives; passive voice uses adverbs'], answer: 1 }
  ],
  // TEST 6
  [
    { id: 76, subject: 'English', grade: 4, question: 'Which word is a common noun?', options: ['Sarah', 'Monday', 'teacher', 'Chicago'], answer: 2 },
    { id: 77, subject: 'English', grade: 4, question: 'What is the contraction for "do not"?', options: ['dont', 'do\'nt', 'don\'t', 'donot'], answer: 2 },
    { id: 78, subject: 'English', grade: 5, question: 'Which word has a prefix?', options: ['jumping', 'redo', 'quickly', 'happiness'], answer: 1 },
    { id: 79, subject: 'English', grade: 5, question: 'What is the comparative form of "good"?', options: ['gooder', 'more good', 'better', 'best'], answer: 2 },
    { id: 80, subject: 'English', grade: 6, question: 'What is a compound sentence?', options: ['A sentence with one independent clause', 'A sentence with two independent clauses joined by a conjunction', 'A sentence with a dependent clause', 'A sentence that asks a question'], answer: 1 },
    { id: 81, subject: 'English', grade: 6, question: 'Which sentence uses "you\'re" correctly?', options: ['You\'re dog is cute.', 'You\'re going to love this.', 'Is that you\'re book?', 'You\'re house is big.'], answer: 1 },
    { id: 82, subject: 'English', grade: 7, question: 'What is a pun?', options: ['An extreme exaggeration', 'A play on words with multiple meanings', 'A comparison using "like"', 'A contradictory phrase'], answer: 1 },
    { id: 83, subject: 'English', grade: 7, question: 'What is the purpose of a thesis statement?', options: ['To provide background information', 'To present the main argument or claim of an essay', 'To summarize the conclusion', 'To list supporting evidence'], answer: 1 },
    { id: 84, subject: 'English', grade: 8, question: 'What does the root "scrib" or "script" mean?', options: ['read', 'speak', 'write', 'think'], answer: 2 },
    { id: 85, subject: 'English', grade: 8, question: 'Which sentence avoids a comma splice?', options: ['I went to the store, I bought milk.', 'I went to the store; I bought milk.', 'I went to the store, bought milk.', 'Both B and C are correct.'], answer: 3 },
    { id: 86, subject: 'English', grade: 9, question: 'What is foreshadowing?', options: ['A flashback to an earlier event', 'Hints or clues about what will happen later in a story', 'The moral of a story', 'The climax of a narrative'], answer: 1 },
    { id: 87, subject: 'English', grade: 9, question: 'What is the difference between a static and dynamic character?', options: ['Static characters are main characters; dynamic characters are minor', 'Static characters do not change; dynamic characters undergo significant change', 'There is no difference', 'Static characters are good; dynamic characters are evil'], answer: 1 },
    { id: 88, subject: 'English', grade: 10, question: 'What is a circular reasoning fallacy?', options: ['Using evidence from experts', 'Using the conclusion as a premise to support itself', 'Making a generalization from one example', 'Attacking the person instead of the argument'], answer: 1 },
    { id: 89, subject: 'English', grade: 10, question: 'What does the psychoanalytic critical lens focus on?', options: ['Historical context of the work', 'Unconscious desires, motivations, and psychological conflicts of characters', 'The formal structure of the text', 'Economic and class issues'], answer: 1 },
    { id: 90, subject: 'English', grade: 5, question: 'What is the superlative form of "fast"?', options: ['faster', 'more fast', 'fastest', 'most fast'], answer: 2 }
  ],
  // TEST 7
  [
    { id: 91, subject: 'English', grade: 4, question: 'Which word rhymes with "cat"?', options: ['cut', 'bat', 'cot', 'kit'], answer: 1 },
    { id: 92, subject: 'English', grade: 4, question: 'What is the correct way to begin a sentence?', options: ['with a lowercase letter', 'with a capital letter', 'with a number', 'with a comma'], answer: 1 },
    { id: 93, subject: 'English', grade: 5, question: 'Which word is a helping verb in "She is running fast"?', options: ['She', 'is', 'running', 'fast'], answer: 1 },
    { id: 94, subject: 'English', grade: 5, question: 'What does the prefix "mis-" mean?', options: ['again', 'not', 'wrongly', 'before'], answer: 2 },
    { id: 95, subject: 'English', grade: 6, question: 'Which sentence uses a comma correctly after an introductory phrase?', options: ['After dinner we played games.', 'After dinner, we played games.', 'After, dinner we played games.', 'After dinner we, played games.'], answer: 1 },
    { id: 96, subject: 'English', grade: 6, question: 'What is an indefinite pronoun?', options: ['A pronoun that refers to a specific person', 'A pronoun that does not refer to a specific person or thing', 'A pronoun used in questions', 'A pronoun that shows ownership'], answer: 1 },
    { id: 97, subject: 'English', grade: 7, question: 'What is personification?', options: ['A comparison using "like" or "as"', 'An extreme exaggeration', 'Giving human qualities to non-human things', 'A reference to a famous person'], answer: 2 },
    { id: 98, subject: 'English', grade: 7, question: 'What is the difference between "who" and "whom"?', options: ['"Who" is for objects; "whom" is for subjects', '"Who" is for subjects; "whom" is for objects', 'They are interchangeable', '"Who" is formal; "whom" is informal'], answer: 1 },
    { id: 99, subject: 'English', grade: 8, question: 'What does the root "chron" mean?', options: ['color', 'time', 'life', 'earth'], answer: 1 },
    { id: 100, subject: 'English', grade: 8, question: 'What is a run-on sentence?', options: ['A sentence that is too short', 'Two or more independent clauses joined without proper punctuation or conjunction', 'A sentence with too many adjectives', 'A sentence fragment'], answer: 1 },
    { id: 101, subject: 'English', grade: 9, question: 'What is symbolism?', options: ['Using a person to represent an idea', 'Using an object, person, or event to represent a deeper meaning', 'A type of simile', 'Repeating a word for emphasis'], answer: 1 },
    { id: 102, subject: 'English', grade: 9, question: 'What is an unreliable narrator?', options: ['A narrator who tells the story in third person', 'A narrator whose account of events cannot be fully trusted', 'A narrator who speaks directly to the reader', 'A narrator who knows everything'], answer: 1 },
    { id: 103, subject: 'English', grade: 10, question: 'What is a bandwagon fallacy?', options: ['Arguing something is true because an expert said so', 'Arguing something is true because everyone believes it', 'Arguing something is true because it has always been done that way', 'Arguing by attacking the person'], answer: 1 },
    { id: 104, subject: 'English', grade: 10, question: 'What does formalist criticism focus on?', options: ['The author\'s biography', 'The historical context', 'The text itself—its structure, language, and literary devices', 'The reader\'s personal response'], answer: 2 },
    { id: 105, subject: 'English', grade: 6, question: 'What part of speech is "and"?', options: ['preposition', 'conjunction', 'adverb', 'pronoun'], answer: 1 }
  ],
  // TEST 8
  [
    { id: 106, subject: 'English', grade: 4, question: 'How many syllables are in the word "elephant"?', options: ['1', '2', '3', '4'], answer: 2 },
    { id: 107, subject: 'English', grade: 4, question: 'Which sentence is written correctly?', options: ['him went to the store.', 'He went to the store.', 'He goed to the store.', 'Him goed to the store.'], answer: 1 },
    { id: 108, subject: 'English', grade: 5, question: 'What is an antonym?', options: ['A word with the same meaning', 'A word with the opposite meaning', 'A word that sounds the same', 'A word with multiple meanings'], answer: 1 },
    { id: 109, subject: 'English', grade: 5, question: 'Which word has a suffix?', options: ['unhappy', 'preview', 'slowly', 'inside'], answer: 2 },
    { id: 110, subject: 'English', grade: 6, question: 'What is a simple sentence?', options: ['A sentence with two independent clauses', 'A sentence with one independent clause', 'A sentence with a dependent and independent clause', 'A sentence that asks a question'], answer: 1 },
    { id: 111, subject: 'English', grade: 6, question: 'Which word is a relative pronoun?', options: ['they', 'which', 'however', 'because'], answer: 1 },
    { id: 112, subject: 'English', grade: 7, question: 'What is an idiom?', options: ['A literal expression', 'A phrase whose meaning is different from the literal meaning of its words', 'A type of simile', 'A grammatical error'], answer: 1 },
    { id: 113, subject: 'English', grade: 7, question: 'What is the purpose of a transitional phrase?', options: ['To end a paragraph', 'To connect ideas between sentences or paragraphs', 'To introduce a thesis', 'To provide a citation'], answer: 1 },
    { id: 114, subject: 'English', grade: 8, question: 'What does the prefix "anti-" mean?', options: ['for', 'before', 'against', 'with'], answer: 2 },
    { id: 115, subject: 'English', grade: 8, question: 'Which sentence uses a gerund?', options: ['She is running.', 'Running is great exercise.', 'She ran quickly.', 'The running water is cold.'], answer: 1 },
    { id: 116, subject: 'English', grade: 9, question: 'What is a motif in literature?', options: ['The main character', 'A recurring element that has symbolic significance', 'The setting of a story', 'The climax of a plot'], answer: 1 },
    { id: 117, subject: 'English', grade: 9, question: 'What type of irony occurs when the audience knows something a character does not?', options: ['verbal irony', 'situational irony', 'dramatic irony', 'cosmic irony'], answer: 2 },
    { id: 118, subject: 'English', grade: 10, question: 'What is an appeal to authority fallacy?', options: ['Using evidence from a relevant expert', 'Claiming something is true solely because an authority figure said so, even if they lack relevant expertise', 'Citing statistics', 'Using logical reasoning'], answer: 1 },
    { id: 119, subject: 'English', grade: 10, question: 'In reader-response criticism, meaning is primarily determined by whom?', options: ['The author', 'The text itself', 'The reader', 'The historical context'], answer: 2 },
    { id: 120, subject: 'English', grade: 7, question: 'What is the meaning of the idiom "break the ice"?', options: ['To literally break ice', 'To initiate conversation in a social setting', 'To cause damage', 'To cool down'], answer: 1 }
  ],
  // TEST 9
  [
    { id: 121, subject: 'English', grade: 4, question: 'Which sentence uses "to," "too," or "two" correctly?', options: ['I have to cats.', 'I want too go home.', 'She has two brothers.', 'He is to tall.'], answer: 2 },
    { id: 122, subject: 'English', grade: 4, question: 'What type of word describes a noun?', options: ['verb', 'adverb', 'adjective', 'conjunction'], answer: 2 },
    { id: 123, subject: 'English', grade: 5, question: 'What is a possessive noun?', options: ['A noun that shows action', 'A noun that shows ownership', 'A noun that names a place', 'A noun that is plural'], answer: 1 },
    { id: 124, subject: 'English', grade: 5, question: 'Which sentence has correct subject-verb agreement?', options: ['The dogs runs fast.', 'The dog run fast.', 'The dogs run fast.', 'The dog are fast.'], answer: 2 },
    { id: 125, subject: 'English', grade: 6, question: 'What is a predicate adjective?', options: ['An adjective before a noun', 'An adjective that follows a linking verb and describes the subject', 'An adjective that modifies a verb', 'An adjective in a prepositional phrase'], answer: 1 },
    { id: 126, subject: 'English', grade: 6, question: 'Which word is a demonstrative pronoun?', options: ['she', 'this', 'who', 'some'], answer: 1 },
    { id: 127, subject: 'English', grade: 7, question: 'What is assonance?', options: ['Repetition of consonant sounds at the beginning of words', 'Repetition of vowel sounds within words', 'A comparison without "like" or "as"', 'Words that imitate sounds'], answer: 1 },
    { id: 128, subject: 'English', grade: 7, question: 'Which is an example of a compound-complex sentence?', options: ['I like tea.', 'I like tea, and she likes coffee.', 'Although I like tea, I drank coffee, and she had water.', 'Although I like tea, I drank coffee.'], answer: 2 },
    { id: 129, subject: 'English', grade: 8, question: 'What does the root "graph" mean?', options: ['speak', 'write', 'see', 'think'], answer: 1 },
    { id: 130, subject: 'English', grade: 8, question: 'What is a participial phrase?', options: ['A phrase that begins with a preposition', 'A phrase that begins with a participle and acts as an adjective', 'A phrase that contains a subject and verb', 'A phrase that functions as a noun'], answer: 1 },
    { id: 131, subject: 'English', grade: 9, question: 'What is verbal irony?', options: ['When the audience knows something the character does not', 'When someone says the opposite of what they mean', 'When the outcome is opposite of what is expected', 'When a story has an unexpected ending'], answer: 1 },
    { id: 132, subject: 'English', grade: 9, question: 'What is the climax of a story?', options: ['The beginning of the story', 'The turning point or moment of highest tension', 'The resolution of the conflict', 'The introduction of characters'], answer: 1 },
    { id: 133, subject: 'English', grade: 10, question: 'What is a false dilemma fallacy?', options: ['Presenting only two options when more exist', 'Making a generalization from one example', 'Attacking the person', 'Using emotional language'], answer: 0 },
    { id: 134, subject: 'English', grade: 10, question: 'What does postcolonial criticism examine?', options: ['The psychological state of the author', 'The effects of colonialism and imperialism on literature and culture', 'The formal structure of texts', 'The universal archetypes in stories'], answer: 1 },
    { id: 135, subject: 'English', grade: 8, question: 'What does the suffix "-tion" or "-sion" typically indicate?', options: ['A verb', 'An adjective', 'A noun indicating an action or state', 'An adverb'], answer: 2 }
  ],
  // TEST 10
  [
    { id: 136, subject: 'English', grade: 4, question: 'Which word is a possessive pronoun?', options: ['he', 'his', 'him', 'himself'], answer: 1 },
    { id: 137, subject: 'English', grade: 4, question: 'What is the future tense of "eat"?', options: ['ate', 'eating', 'will eat', 'eaten'], answer: 2 },
    { id: 138, subject: 'English', grade: 5, question: 'What is an irregular verb?', options: ['A verb that follows standard conjugation rules', 'A verb that does not follow standard conjugation rules', 'A verb that is always in present tense', 'A verb that only has one form'], answer: 1 },
    { id: 139, subject: 'English', grade: 5, question: 'Which sentence uses a comma correctly in a compound sentence?', options: ['I like pizza, it is delicious.', 'I like pizza and it is delicious.', 'I like pizza, and it is delicious.', 'I like, pizza and it is delicious.'], answer: 2 },
    { id: 140, subject: 'English', grade: 6, question: 'What is a subordinating conjunction?', options: ['A word that joins two independent clauses', 'A word that introduces a dependent clause', 'A word that joins a noun and a verb', 'A word that replaces a noun'], answer: 1 },
    { id: 141, subject: 'English', grade: 6, question: 'Which is an example of a subordinating conjunction?', options: ['and', 'but', 'because', 'or'], answer: 2 },
    { id: 142, subject: 'English', grade: 7, question: 'What is consonance?', options: ['Repetition of vowel sounds', 'Repetition of consonant sounds within or at the end of words', 'Words that rhyme', 'Words that imitate sounds'], answer: 1 },
    { id: 143, subject: 'English', grade: 7, question: 'What is a sentence fragment?', options: ['A complete sentence', 'An incomplete sentence missing a subject or verb', 'A very long sentence', 'A sentence with two clauses'], answer: 1 },
    { id: 144, subject: 'English', grade: 8, question: 'What does the root "bio" mean?', options: ['earth', 'water', 'life', 'light'], answer: 2 },
    { id: 145, subject: 'English', grade: 8, question: 'Which sentence correctly uses an infinitive phrase?', options: ['To run is difficult.', 'She wants running.', 'To quickly he ran.', 'For run he went.'], answer: 0 },
    { id: 146, subject: 'English', grade: 9, question: 'What is a foil character?', options: ['The main character of a story', 'A character who contrasts with another character to highlight their qualities', 'The villain of a story', 'A character who narrates'], answer: 1 },
    { id: 147, subject: 'English', grade: 9, question: 'What is the resolution of a story?', options: ['The introduction of the conflict', 'The rising action', 'The part where the conflict is resolved and loose ends are tied up', 'The climax'], answer: 2 },
    { id: 148, subject: 'English', grade: 10, question: 'What is the appeal to tradition fallacy?', options: ['Arguing something is right because it is new', 'Arguing something is right because it has always been done that way', 'Arguing something is right because an expert says so', 'Arguing something is right because it is popular'], answer: 1 },
    { id: 149, subject: 'English', grade: 10, question: 'What does the historical-biographical critical lens focus on?', options: ['The text in isolation', 'The author\'s life and the historical context in which the work was written', 'The reader\'s interpretation', 'The unconscious motivations of characters'], answer: 1 },
    { id: 150, subject: 'English', grade: 9, question: 'What is situational irony?', options: ['When someone says the opposite of what they mean', 'When the audience knows something a character does not', 'When the outcome is the opposite of what is expected', 'When dialogue contradicts the setting'], answer: 2 }
  ],
];

module.exports = { englishTestBanks };
