const geographyTestBanks = [
// Test 1
[
{id:1,subject:'Geography',grade:4,question:'How many continents are there on Earth?',options:['5','6','7','8'],answer:2},
{id:2,subject:'Geography',grade:4,question:'Which ocean is the largest?',options:['Atlantic','Indian','Arctic','Pacific'],answer:3},
{id:3,subject:'Geography',grade:5,question:'What is the longest river in the world?',options:['Amazon','Nile','Mississippi','Yangtze'],answer:1},
{id:4,subject:'Geography',grade:5,question:'Which continent is the Sahara Desert located on?',options:['Asia','South America','Africa','Australia'],answer:2},
{id:5,subject:'Geography',grade:6,question:'What does a map legend show?',options:['Directions','Symbols and their meanings','Distance only','Weather patterns'],answer:1},
{id:6,subject:'Geography',grade:6,question:'Lines of latitude run in which direction?',options:['North to south','East to west','Diagonally','They curve'],answer:1},
{id:7,subject:'Geography',grade:7,question:'What is the capital of Australia?',options:['Sydney','Melbourne','Canberra','Perth'],answer:2},
{id:8,subject:'Geography',grade:7,question:'Which mountain range separates Europe from Asia?',options:['Alps','Himalayas','Ural Mountains','Andes'],answer:2},
{id:9,subject:'Geography',grade:8,question:'What is the most populated country in Africa?',options:['Egypt','South Africa','Ethiopia','Nigeria'],answer:3},
{id:10,subject:'Geography',grade:8,question:'Which US state is the largest by area?',options:['Texas','California','Montana','Alaska'],answer:3},
{id:11,subject:'Geography',grade:9,question:'What is urbanization?',options:['Movement from cities to farms','Growth of city populations','Decrease in population','Building of highways'],answer:1},
{id:12,subject:'Geography',grade:9,question:'Which climate zone is found near the equator?',options:['Temperate','Polar','Tropical','Arid'],answer:2},
{id:13,subject:'Geography',grade:10,question:'What does GIS stand for?',options:['Global Internet System','Geographic Information System','General Infrastructure Service','Geological Index Survey'],answer:1},
{id:14,subject:'Geography',grade:10,question:'The concept of cultural diffusion refers to what?',options:['Isolation of cultures','Spread of cultural traits from one society to another','Government policies on culture','Population decline'],answer:1},
{id:15,subject:'Geography',grade:4,question:'Which continent do penguins primarily live on in the wild?',options:['North America','Europe','Antarctica','Asia'],answer:2}
],
// Test 2
[
{id:16,subject:'Geography',grade:4,question:'Which ocean lies between North America and Europe?',options:['Pacific','Indian','Atlantic','Arctic'],answer:2},
{id:17,subject:'Geography',grade:4,question:'What is the smallest continent?',options:['Europe','Antarctica','Australia','South America'],answer:2},
{id:18,subject:'Geography',grade:5,question:'The Grand Canyon is located in which US state?',options:['Utah','Colorado','Nevada','Arizona'],answer:3},
{id:19,subject:'Geography',grade:5,question:'What type of landform is surrounded by water on three sides?',options:['Island','Peninsula','Isthmus','Cape'],answer:1},
{id:20,subject:'Geography',grade:6,question:'What is the Prime Meridian?',options:['The equator','0 degrees longitude','The International Date Line','The Tropic of Cancer'],answer:1},
{id:21,subject:'Geography',grade:6,question:'A political map primarily shows what?',options:['Mountains and rivers','Weather patterns','Borders and cities','Ocean currents'],answer:2},
{id:22,subject:'Geography',grade:7,question:'Which river flows through Egypt?',options:['Congo','Niger','Nile','Zambezi'],answer:2},
{id:23,subject:'Geography',grade:7,question:'What is the largest desert in Asia?',options:['Thar','Karakum','Gobi','Arabian'],answer:2},
{id:24,subject:'Geography',grade:8,question:'What is the Ring of Fire?',options:['A volcanic zone in Africa','A zone of earthquakes and volcanoes around the Pacific Ocean','A desert region','A tropical storm belt'],answer:1},
{id:25,subject:'Geography',grade:8,question:'Which Great Lake is the largest by surface area?',options:['Lake Michigan','Lake Erie','Lake Huron','Lake Superior'],answer:3},
{id:26,subject:'Geography',grade:9,question:'What is a megacity?',options:['A city with over 10 million people','Any capital city','A city with skyscrapers','A city older than 500 years'],answer:0},
{id:27,subject:'Geography',grade:9,question:'Which world region is known as the Middle East?',options:['Central Africa','Southeast Asia','Southwest Asia and North Africa','Eastern Europe'],answer:2},
{id:28,subject:'Geography',grade:10,question:'Demographic transition model stage 1 is characterized by what?',options:['High birth and high death rates','Low birth and low death rates','High birth and low death rates','Low birth and high death rates'],answer:0},
{id:29,subject:'Geography',grade:10,question:'What is geopolitics?',options:['Study of soil types','Study of how geography influences politics and international relations','Study of elections','Study of city planning'],answer:1},
{id:30,subject:'Geography',grade:5,question:'What are the Great Plains?',options:['Mountains in Europe','A flat grassland region in central North America','Islands in the Pacific','Forests in South America'],answer:1}
],
// Test 3
[
{id:31,subject:'Geography',grade:4,question:'Which continent is Brazil located on?',options:['North America','Europe','Africa','South America'],answer:3},
{id:32,subject:'Geography',grade:4,question:'What is an island?',options:['Land surrounded by water on all sides','A large lake','A mountain peak','A river delta'],answer:0},
{id:33,subject:'Geography',grade:5,question:'The Rocky Mountains are found on which continent?',options:['South America','Europe','North America','Asia'],answer:2},
{id:34,subject:'Geography',grade:5,question:'What is the largest US state by population?',options:['Texas','New York','Florida','California'],answer:3},
{id:35,subject:'Geography',grade:6,question:'What tool on a map shows direction?',options:['Scale bar','Legend','Compass rose','Title'],answer:2},
{id:36,subject:'Geography',grade:6,question:'The equator divides the Earth into which two hemispheres?',options:['Eastern and Western','Northern and Southern','Pacific and Atlantic','Upper and Lower'],answer:1},
{id:37,subject:'Geography',grade:7,question:'Which country has the largest land area in Africa?',options:['Sudan','Democratic Republic of Congo','Algeria','Libya'],answer:2},
{id:38,subject:'Geography',grade:7,question:'Mount Everest is located in which mountain range?',options:['Andes','Alps','Rockies','Himalayas'],answer:3},
{id:39,subject:'Geography',grade:8,question:'What is a plateau?',options:['A deep valley','A flat elevated area of land','A coastal plain','A volcanic island'],answer:1},
{id:40,subject:'Geography',grade:8,question:'The Mississippi River empties into which body of water?',options:['Atlantic Ocean','Pacific Ocean','Gulf of Mexico','Caribbean Sea'],answer:2},
{id:41,subject:'Geography',grade:9,question:'What is globalization?',options:['Increasing interconnection of world economies and cultures','A type of map projection','The study of globes','A weather phenomenon'],answer:0},
{id:42,subject:'Geography',grade:9,question:'Which climate zone has four distinct seasons?',options:['Tropical','Arid','Temperate','Polar'],answer:2},
{id:43,subject:'Geography',grade:10,question:'European imperialism in Africa during the 1800s is often associated with what event?',options:['The Silk Road','The Scramble for Africa','The Industrial Revolution','The Renaissance'],answer:1},
{id:44,subject:'Geography',grade:10,question:'What does a choropleth map display?',options:['Road networks','Elevation only','Data values using color shading across areas','Wind patterns'],answer:2},
{id:45,subject:'Geography',grade:6,question:'What is the difference between latitude and longitude?',options:['They are the same thing','Latitude measures north-south position; longitude measures east-west','Latitude measures east-west; longitude measures north-south','Neither measures position'],answer:1}
],
// Test 4
[
{id:46,subject:'Geography',grade:4,question:'Which ocean is the coldest?',options:['Pacific','Atlantic','Indian','Arctic'],answer:3},
{id:47,subject:'Geography',grade:4,question:'On which continent is China located?',options:['Europe','Africa','Asia','Australia'],answer:2},
{id:48,subject:'Geography',grade:5,question:'What is a volcano?',options:['A deep ocean trench','An opening in the Earth\'s surface where lava erupts','A type of river','A flat desert'],answer:1},
{id:49,subject:'Geography',grade:5,question:'Which US region is known as the Midwest?',options:['California and Oregon','New York and New Jersey','Ohio, Illinois, Iowa and surrounding states','Texas and Louisiana'],answer:2},
{id:50,subject:'Geography',grade:6,question:'A map scale helps you determine what?',options:['Temperature','Real-world distance','Population','Elevation'],answer:1},
{id:51,subject:'Geography',grade:6,question:'The Tropic of Cancer is located at approximately what latitude?',options:['23.5°N','23.5°S','66.5°N','0°'],answer:0},
{id:52,subject:'Geography',grade:7,question:'What is the longest river in Asia?',options:['Ganges','Mekong','Yangtze','Indus'],answer:2},
{id:53,subject:'Geography',grade:7,question:'Which African country is known as the Horn of Africa along with its neighbors?',options:['Nigeria','South Africa','Somalia','Morocco'],answer:2},
{id:54,subject:'Geography',grade:8,question:'What is the Continental Divide in North America?',options:['The border between US and Canada','A ridge that separates river systems flowing to different oceans','The Mississippi River','The Appalachian Trail'],answer:1},
{id:55,subject:'Geography',grade:8,question:'Which country has the most people in the world?',options:['United States','Indonesia','India','China'],answer:2},
{id:56,subject:'Geography',grade:9,question:'What is rural-to-urban migration?',options:['Moving from one country to another','Moving from the city to the countryside','Moving from the countryside to the city','Moving between two rural areas'],answer:2},
{id:57,subject:'Geography',grade:9,question:'The Sahel region in Africa is best described as what?',options:['Tropical rainforest','Semi-arid transition zone south of the Sahara','Tundra','Coastal wetland'],answer:1},
{id:58,subject:'Geography',grade:10,question:'What is the Heartland Theory in geopolitics?',options:['Whoever controls the central Eurasian landmass controls the world','Sea power is most important','Air power determines geopolitics','Small nations are always strongest'],answer:0},
{id:59,subject:'Geography',grade:10,question:'The demographic transition model has how many stages?',options:['3','4','5','6'],answer:2},
{id:60,subject:'Geography',grade:7,question:'Lake Victoria is located on which continent?',options:['South America','Asia','Europe','Africa'],answer:3}
],
// Test 5
[
{id:61,subject:'Geography',grade:4,question:'What are the four cardinal directions?',options:['Up, Down, Left, Right','North, South, East, West','Forward, Backward, Left, Right','Top, Bottom, Front, Back'],answer:1},
{id:62,subject:'Geography',grade:4,question:'Which continent is the largest by land area?',options:['Africa','North America','Asia','Europe'],answer:2},
{id:63,subject:'Geography',grade:5,question:'The Appalachian Mountains are located in which part of the United States?',options:['West','Central','East','Southwest'],answer:2},
{id:64,subject:'Geography',grade:5,question:'What is a glacier?',options:['A hot spring','A large slow-moving mass of ice','A type of volcano','A desert sand dune'],answer:1},
{id:65,subject:'Geography',grade:6,question:'What does a physical map show?',options:['Borders and capitals','Natural features like mountains and rivers','Population data','Trade routes'],answer:1},
{id:66,subject:'Geography',grade:6,question:'At what degree of latitude is the equator?',options:['90°','45°','23.5°','0°'],answer:3},
{id:67,subject:'Geography',grade:7,question:'Which Asian country is an archipelago of over 17,000 islands?',options:['Philippines','Japan','Indonesia','Malaysia'],answer:2},
{id:68,subject:'Geography',grade:7,question:'The Andes Mountains are located on which continent?',options:['Europe','Asia','Africa','South America'],answer:3},
{id:69,subject:'Geography',grade:8,question:'What is the largest country by area in South America?',options:['Argentina','Colombia','Peru','Brazil'],answer:3},
{id:70,subject:'Geography',grade:8,question:'The Great Barrier Reef is found off the coast of which country?',options:['Indonesia','Australia','Philippines','New Zealand'],answer:1},
{id:71,subject:'Geography',grade:9,question:'What type of economy relies primarily on agriculture and raw materials?',options:['Industrial economy','Post-industrial economy','Primary economy','Service economy'],answer:2},
{id:72,subject:'Geography',grade:9,question:'What is a monsoon?',options:['A type of earthquake','A seasonal wind that brings heavy rain','A volcanic eruption','A cold ocean current'],answer:1},
{id:73,subject:'Geography',grade:10,question:'What is cultural diffusion through trade known as?',options:['Relocation diffusion','Stimulus diffusion','Contagious diffusion','Economic diffusion'],answer:2},
{id:74,subject:'Geography',grade:10,question:'What is a supranational organization?',options:['A single country\'s government','An organization where multiple countries cooperate and give up some sovereignty','A city government','A local community group'],answer:1},
{id:75,subject:'Geography',grade:8,question:'Which US city is known as the Windy City?',options:['New York','Los Angeles','Chicago','Houston'],answer:2}
],
// Test 6
[
{id:76,subject:'Geography',grade:4,question:'What is the name of the imaginary line that divides the Earth into Eastern and Western Hemispheres?',options:['Equator','Tropic of Capricorn','Prime Meridian','Date Line'],answer:2},
{id:77,subject:'Geography',grade:4,question:'Which ocean borders the west coast of the United States?',options:['Atlantic','Pacific','Indian','Arctic'],answer:1},
{id:78,subject:'Geography',grade:5,question:'What is a peninsula?',options:['An island chain','Land surrounded by water on three sides','A mountain range','A deep valley'],answer:1},
{id:79,subject:'Geography',grade:5,question:'Florida is a peninsula. Which body of water is to its east?',options:['Gulf of Mexico','Pacific Ocean','Atlantic Ocean','Caribbean Sea'],answer:2},
{id:80,subject:'Geography',grade:6,question:'Lines of longitude are also called what?',options:['Parallels','Meridians','Tropics','Circles'],answer:1},
{id:81,subject:'Geography',grade:6,question:'A topographic map uses contour lines to show what?',options:['Population density','Political borders','Elevation changes','Climate zones'],answer:2},
{id:82,subject:'Geography',grade:7,question:'Which is the smallest country in the world by land area?',options:['Monaco','Liechtenstein','Vatican City','San Marino'],answer:2},
{id:83,subject:'Geography',grade:7,question:'The Amazon Rainforest is primarily in which country?',options:['Peru','Colombia','Venezuela','Brazil'],answer:3},
{id:84,subject:'Geography',grade:8,question:'What is the tallest mountain in North America?',options:['Mount Rainier','Mount Whitney','Denali','Mount Elbert'],answer:2},
{id:85,subject:'Geography',grade:8,question:'What is an archipelago?',options:['A large desert','A chain of islands','A mountain pass','A river delta'],answer:1},
{id:86,subject:'Geography',grade:9,question:'What is the push-pull theory of migration?',options:['A theory about plate tectonics','Factors that push people from one place and pull them to another','A theory about ocean currents','A farming technique'],answer:1},
{id:87,subject:'Geography',grade:9,question:'Sub-Saharan Africa refers to the part of Africa located where?',options:['North of the Sahara','South of the Sahara','Only coastal Africa','Only island nations'],answer:1},
{id:88,subject:'Geography',grade:10,question:'What is devolution in political geography?',options:['Transfer of power from central to regional governments','Merging of countries','Colonial expansion','Economic growth'],answer:0},
{id:89,subject:'Geography',grade:10,question:'What is the Green Revolution?',options:['Planting trees in deserts','Major increase in agricultural production through technology','Recycling programs','Solar energy adoption'],answer:1},
{id:90,subject:'Geography',grade:5,question:'What is the capital of the United States?',options:['New York City','Los Angeles','Washington, D.C.','Chicago'],answer:2}
],
// Test 7
[
{id:91,subject:'Geography',grade:4,question:'Which continent is entirely in the Southern Hemisphere?',options:['Europe','North America','Antarctica','Asia'],answer:2},
{id:92,subject:'Geography',grade:4,question:'A globe is a model of what?',options:['The Moon','The Sun','The Earth','A continent'],answer:2},
{id:93,subject:'Geography',grade:5,question:'The Great Lakes are located between the US and which country?',options:['Mexico','Cuba','Canada','Greenland'],answer:2},
{id:94,subject:'Geography',grade:5,question:'What is a delta?',options:['A mountain peak','Land formed at the mouth of a river','A desert oasis','A frozen lake'],answer:1},
{id:95,subject:'Geography',grade:6,question:'The International Date Line is roughly at what longitude?',options:['0°','90°','180°','45°'],answer:2},
{id:96,subject:'Geography',grade:6,question:'Which hemisphere is South America mostly in?',options:['Northern and Eastern','Southern and Western','Northern and Western','Southern and Eastern'],answer:1},
{id:97,subject:'Geography',grade:7,question:'What is the driest continent on Earth?',options:['Africa','Australia','Antarctica','South America'],answer:2},
{id:98,subject:'Geography',grade:7,question:'The Ganges River is sacred to which religion?',options:['Islam','Christianity','Buddhism','Hinduism'],answer:3},
{id:99,subject:'Geography',grade:8,question:'Which country is both in Europe and Asia?',options:['Russia','Egypt','India','Greece'],answer:0},
{id:100,subject:'Geography',grade:8,question:'What is the most spoken language in South America?',options:['English','Spanish','Portuguese','French'],answer:1},
{id:101,subject:'Geography',grade:9,question:'What is a primate city?',options:['A city with a zoo','The largest city in a country that is disproportionately larger than others','The oldest city','A capital city'],answer:1},
{id:102,subject:'Geography',grade:9,question:'The Koppen climate classification system categorizes climates based on what?',options:['Elevation only','Temperature and precipitation','Wind speed','Soil type'],answer:1},
{id:103,subject:'Geography',grade:10,question:'What was the Berlin Conference of 1884-1885 about?',options:['Ending World War I','European partitioning of Africa','Formation of the EU','Building the Berlin Wall'],answer:1},
{id:104,subject:'Geography',grade:10,question:'What is spatial analysis in GIS?',options:['Drawing maps by hand','Using software to analyze geographic patterns and relationships','Measuring rainfall','Taking photographs'],answer:1},
{id:105,subject:'Geography',grade:6,question:'What is the difference between weather and climate?',options:['They are the same','Weather is short-term; climate is long-term average','Climate is short-term; weather is long-term','Neither relates to temperature'],answer:1}
],
// Test 8
[
{id:106,subject:'Geography',grade:4,question:'What is the largest ocean on Earth?',options:['Atlantic','Indian','Arctic','Pacific'],answer:3},
{id:107,subject:'Geography',grade:4,question:'On which continent would you find kangaroos in the wild?',options:['Africa','South America','Australia','Asia'],answer:2},
{id:108,subject:'Geography',grade:5,question:'What US state is made up entirely of islands?',options:['Alaska','Florida','Hawaii','Rhode Island'],answer:2},
{id:109,subject:'Geography',grade:5,question:'What is an isthmus?',options:['A large island','A narrow strip of land connecting two larger landmasses','A wide river','A mountain chain'],answer:1},
{id:110,subject:'Geography',grade:6,question:'The Tropic of Capricorn is at approximately what latitude?',options:['23.5°N','23.5°S','66.5°S','0°'],answer:1},
{id:111,subject:'Geography',grade:6,question:'A thematic map shows what kind of information?',options:['Only roads','Only borders','A specific topic like climate or population','Only elevation'],answer:2},
{id:112,subject:'Geography',grade:7,question:'Which is the most populous country in Southeast Asia?',options:['Thailand','Vietnam','Philippines','Indonesia'],answer:3},
{id:113,subject:'Geography',grade:7,question:'The Sahara Desert stretches across how many African countries?',options:['3','5','8','11'],answer:3},
{id:114,subject:'Geography',grade:8,question:'What is the capital of Canada?',options:['Toronto','Vancouver','Montreal','Ottawa'],answer:3},
{id:115,subject:'Geography',grade:8,question:'Pangaea was what?',options:['An ancient ocean','A supercontinent that existed millions of years ago','A volcanic island','An ice age'],answer:1},
{id:116,subject:'Geography',grade:9,question:'What does HDI stand for in geography?',options:['High Density Index','Human Development Index','Horizontal Distance Indicator','Hydrological Data Index'],answer:1},
{id:117,subject:'Geography',grade:9,question:'Which biome covers the most land area on Earth?',options:['Desert','Tropical rainforest','Taiga (boreal forest)','Grassland'],answer:2},
{id:118,subject:'Geography',grade:10,question:'What is neo-colonialism?',options:['Direct military occupation','Indirect economic and political influence over developing nations','Ancient Roman colonization','Space colonization'],answer:1},
{id:119,subject:'Geography',grade:10,question:'Remote sensing in GIS involves what?',options:['Sending emails','Gathering data about Earth from satellites or aircraft','Using a compass','Reading old maps'],answer:1},
{id:120,subject:'Geography',grade:7,question:'Which strait separates Europe from Africa?',options:['Strait of Hormuz','Strait of Malacca','Strait of Gibraltar','Bering Strait'],answer:2}
],
// Test 9
[
{id:121,subject:'Geography',grade:4,question:'Which direction does the sun rise from?',options:['West','North','East','South'],answer:2},
{id:122,subject:'Geography',grade:4,question:'How many oceans are there on Earth?',options:['3','4','5','6'],answer:2},
{id:123,subject:'Geography',grade:5,question:'What is the tallest mountain in the world?',options:['K2','Kangchenjunga','Mount Everest','Makalu'],answer:2},
{id:124,subject:'Geography',grade:5,question:'Which river is the longest in North America?',options:['Colorado','Mississippi-Missouri','Rio Grande','Columbia'],answer:1},
{id:125,subject:'Geography',grade:6,question:'What are latitude lines also called?',options:['Meridians','Parallels','Contours','Axes'],answer:1},
{id:126,subject:'Geography',grade:6,question:'Which type of map projection preserves area accurately?',options:['Mercator','Robinson','Equal-area (Peters)','Azimuthal'],answer:2},
{id:127,subject:'Geography',grade:7,question:'What country in Asia has the largest population?',options:['India','Japan','Indonesia','China'],answer:0},
{id:128,subject:'Geography',grade:7,question:'The Congo River is located on which continent?',options:['South America','Asia','Africa','Europe'],answer:2},
{id:129,subject:'Geography',grade:8,question:'What is a fjord?',options:['A flat plain','A narrow inlet of sea between steep cliffs','A sand dune','A type of glacier'],answer:1},
{id:130,subject:'Geography',grade:8,question:'The Panama Canal connects which two bodies of water?',options:['Atlantic and Indian Oceans','Pacific and Arctic Oceans','Atlantic and Pacific Oceans','Indian and Pacific Oceans'],answer:2},
{id:131,subject:'Geography',grade:9,question:'What is desertification?',options:['Building deserts','The process of fertile land becoming desert','Irrigating deserts','Desert tourism'],answer:1},
{id:132,subject:'Geography',grade:9,question:'What is an urban heat island?',options:['A tropical city','A city that is warmer than surrounding rural areas','A volcanic island with a city','A hot desert town'],answer:1},
{id:133,subject:'Geography',grade:10,question:'What is balkanization?',options:['Tourism in the Balkans','Fragmentation of a region into smaller hostile units','A cooking style','Building bridges'],answer:1},
{id:134,subject:'Geography',grade:10,question:'In the demographic transition model, which stage sees rapidly declining death rates but still high birth rates?',options:['Stage 1','Stage 2','Stage 3','Stage 4'],answer:1},
{id:135,subject:'Geography',grade:5,question:'Which two countries share the longest international border?',options:['US and Mexico','Russia and China','US and Canada','Brazil and Argentina'],answer:2}
],
// Test 10
[
{id:136,subject:'Geography',grade:4,question:'What do we call a large body of saltwater?',options:['Lake','River','Ocean','Pond'],answer:2},
{id:137,subject:'Geography',grade:4,question:'Which continent has the most countries?',options:['Asia','Europe','Africa','South America'],answer:2},
{id:138,subject:'Geography',grade:5,question:'What causes the seasons on Earth?',options:['Distance from the sun','The tilt of Earth\'s axis','The moon\'s gravity','Ocean currents'],answer:1},
{id:139,subject:'Geography',grade:5,question:'Mount Rushmore is located in which US state?',options:['Montana','Wyoming','South Dakota','North Dakota'],answer:2},
{id:140,subject:'Geography',grade:6,question:'What is the Arctic Circle?',options:['A line of latitude at about 66.5°N','The North Pole','A line of longitude','The equator'],answer:0},
{id:141,subject:'Geography',grade:6,question:'A road map is an example of what type of map?',options:['Physical map','Thematic map','Political map','Topographic map'],answer:2},
{id:142,subject:'Geography',grade:7,question:'What is the capital of Japan?',options:['Osaka','Kyoto','Tokyo','Yokohama'],answer:2},
{id:143,subject:'Geography',grade:7,question:'The Nile River flows into which body of water?',options:['Red Sea','Indian Ocean','Mediterranean Sea','Atlantic Ocean'],answer:2},
{id:144,subject:'Geography',grade:8,question:'What is the largest island in the world?',options:['Madagascar','Borneo','New Guinea','Greenland'],answer:3},
{id:145,subject:'Geography',grade:8,question:'The Dust Bowl of the 1930s affected which region of the US?',options:['Northeast','Southeast','Great Plains','Pacific Northwest'],answer:2},
{id:146,subject:'Geography',grade:9,question:'What is a favela?',options:['A festival in Spain','An informal urban settlement in Brazil','A type of farmland','A government building'],answer:1},
{id:147,subject:'Geography',grade:9,question:'What is deforestation?',options:['Planting new forests','Clearing forests for other uses','Studying forests','Protecting forests'],answer:1},
{id:148,subject:'Geography',grade:10,question:'The European Union is an example of what?',options:['A military alliance only','A supranational political and economic union','A single country','A continent'],answer:1},
{id:149,subject:'Geography',grade:10,question:'What is gerrymandering?',options:['A farming technique','Drawing political district boundaries to favor a party','Building geothermal plants','A type of migration'],answer:1},
{id:150,subject:'Geography',grade:8,question:'What natural feature forms the border between the US and Mexico in Texas?',options:['Rocky Mountains','Rio Grande','Colorado River','Gulf of Mexico'],answer:1}
],
// Test 11
[
{id:151,subject:'Geography',grade:4,question:'What are mountains?',options:['Flat areas of land','Large bodies of water','Tall landforms that rise high above surrounding land','Underground caves'],answer:2},
{id:152,subject:'Geography',grade:4,question:'Which continent is directly south of Europe?',options:['Asia','South America','Africa','Antarctica'],answer:2},
{id:153,subject:'Geography',grade:5,question:'What is a tributary?',options:['A main river','A stream or river that flows into a larger river','An ocean current','A waterfall'],answer:1},
{id:154,subject:'Geography',grade:5,question:'The Statue of Liberty is located in which US state?',options:['Massachusetts','New Jersey','New York','Pennsylvania'],answer:2},
{id:155,subject:'Geography',grade:6,question:'What is the purpose of a map grid?',options:['To make maps colorful','To help locate specific places using coordinates','To show elevation','To measure temperature'],answer:1},
{id:156,subject:'Geography',grade:6,question:'The Antarctic Circle is at approximately what latitude?',options:['23.5 degrees S','45 degrees S','66.5 degrees S','90 degrees S'],answer:2},
{id:157,subject:'Geography',grade:7,question:'Which country is the largest in South America by area?',options:['Argentina','Chile','Colombia','Brazil'],answer:3},
{id:158,subject:'Geography',grade:7,question:'What is the Serengeti?',options:['A mountain in Asia','A grassland ecosystem in East Africa','A river in Europe','A desert in Australia'],answer:1},
{id:159,subject:'Geography',grade:8,question:'What tectonic plate does most of North America sit on?',options:['Pacific Plate','Eurasian Plate','North American Plate','Antarctic Plate'],answer:2},
{id:160,subject:'Geography',grade:8,question:'Which US state has the most electoral votes?',options:['Texas','New York','Florida','California'],answer:3},
{id:161,subject:'Geography',grade:9,question:'What is a landlocked country?',options:['A country with many lakes','A country with no coastline','A country that is an island','A country with low elevation'],answer:1},
{id:162,subject:'Geography',grade:9,question:'The tundra biome is characterized by what?',options:['Dense forest','Very cold temperatures and permafrost','Hot and humid conditions','Moderate rainfall year-round'],answer:1},
{id:163,subject:'Geography',grade:10,question:'What is Rostow\'s Stages of Economic Growth model?',options:['A climate model','A model describing five stages of economic development','A population model','A soil classification system'],answer:1},
{id:164,subject:'Geography',grade:10,question:'What is a buffer state?',options:['A wealthy country','A country located between two rival powers','An island nation','A country with strong military'],answer:1},
{id:165,subject:'Geography',grade:7,question:'Which African nation was never colonized by a European power?',options:['Nigeria','Kenya','Ethiopia','Ghana'],answer:2}
],
// Test 12
[
{id:166,subject:'Geography',grade:4,question:'A desert is a place that receives very little what?',options:['Sunlight','Wind','Rainfall','Heat'],answer:2},
{id:167,subject:'Geography',grade:4,question:'Which continent is the second largest by area?',options:['North America','Asia','Africa','Europe'],answer:2},
{id:168,subject:'Geography',grade:5,question:'What is the capital of Mexico?',options:['Guadalajara','Cancun','Monterrey','Mexico City'],answer:3},
{id:169,subject:'Geography',grade:5,question:'The Everglades are located in which US state?',options:['Louisiana','Georgia','South Carolina','Florida'],answer:3},
{id:170,subject:'Geography',grade:6,question:'What is a hemisphere?',options:['A type of mountain','Half of the Earth','A weather pattern','A map symbol'],answer:1},
{id:171,subject:'Geography',grade:6,question:'Mercator projection maps distort what?',options:['Colors','Shapes near equator','Size of areas near the poles','Ocean depths'],answer:2},
{id:172,subject:'Geography',grade:7,question:'Which is the most populous city in Africa?',options:['Cairo','Nairobi','Lagos','Johannesburg'],answer:2},
{id:173,subject:'Geography',grade:7,question:'The Mekong River flows through which region?',options:['Central Asia','Southeast Asia','Middle East','Eastern Europe'],answer:1},
{id:174,subject:'Geography',grade:8,question:'What is erosion?',options:['Building up of soil','Wearing away of land by wind, water, or ice','Growth of vegetation','Movement of tectonic plates'],answer:1},
{id:175,subject:'Geography',grade:8,question:'The Suez Canal connects which two bodies of water?',options:['Atlantic and Pacific','Mediterranean Sea and Red Sea','Black Sea and Caspian Sea','North Sea and Baltic Sea'],answer:1},
{id:176,subject:'Geography',grade:9,question:'What is sustainable development?',options:['Rapid industrialization','Development that meets present needs without compromising future generations','Only using renewable energy','Zero economic growth'],answer:1},
{id:177,subject:'Geography',grade:9,question:'A savanna is best described as what?',options:['Dense forest','Tropical grassland with scattered trees','Frozen tundra','Coastal wetland'],answer:1},
{id:178,subject:'Geography',grade:10,question:'What is a shatterbelt region?',options:['An earthquake zone','A region caught between competing powers and fragmented','A mineral-rich area','A coastal erosion zone'],answer:1},
{id:179,subject:'Geography',grade:10,question:'The spread of fast food chains worldwide is an example of what?',options:['Isolationism','Cultural diffusion through globalization','Demographic transition','Physical weathering'],answer:1},
{id:180,subject:'Geography',grade:6,question:'What is a cartographer?',options:['A person who studies stars','A person who makes maps','A person who studies animals','A person who studies rocks'],answer:1}
],
// Test 13
[
{id:181,subject:'Geography',grade:4,question:'What is a lake?',options:['A body of saltwater','A flowing body of water','A body of water surrounded by land','An underground river'],answer:2},
{id:182,subject:'Geography',grade:4,question:'Which is the only continent that is also a country?',options:['Antarctica','Europe','Africa','Australia'],answer:3},
{id:183,subject:'Geography',grade:5,question:'Niagara Falls is on the border of the US and which country?',options:['Mexico','Canada','Cuba','Greenland'],answer:1},
{id:184,subject:'Geography'
